---

_You are currently looking at **version 1.0** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-text-mining/resources/d9pwm) course resource._

---

# Assignment 1

In this assignment, you'll be working with messy medical data and using regex to extract relevant infromation from the data. 

Each line of the `dates.txt` file corresponds to a medical note. Each note has a date that needs to be extracted, but each date is encoded in one of many formats.

The goal of this assignment is to correctly identify all of the different date variants encoded in this dataset and to properly normalize and sort the dates. 

Here is a list of some of the variants you might encounter in this dataset:
* 04/20/2009; 04/20/09; 4/20/09; 4/3/09
* Mar-20-2009; Mar 20, 2009; March 20, 2009;  Mar. 20, 2009; Mar 20 2009;
* 20 Mar 2009; 20 March 2009; 20 Mar. 2009; 20 March, 2009
* Mar 20th, 2009; Mar 21st, 2009; Mar 22nd, 2009
* Feb 2009; Sep 2009; Oct 2010
* 6/2008; 12/2009
* 2009; 2010

Once you have extracted these date patterns from the text, the next step is to sort them in ascending chronological order accoring to the following rules:
* Assume all dates in xx/xx/xx format are mm/dd/yy
* Assume all dates where year is encoded in only two digits are years from the 1900's (e.g. 1/5/89 is January 5th, 1989)
* If the day is missing (e.g. 9/2009), assume it is the first day of the month (e.g. September 1, 2009).
* If the month is missing (e.g. 2010), assume it is the first of January of that year (e.g. January 1, 2010).

With these rules in mind, find the correct date in each note and return a pandas Series in chronological order of the original Series' indices.

For example if the original series was this:

    0    1999
    1    2010
    2    1978
    3    2015
    4    1985

Your function should return this:

    0    2
    1    4
    2    0
    3    1
    4    3

Your score will be calculated using [Kendall's tau](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient), a correlation measure for ordinal data.

*This function should return a Series of length 500 and dtype int.*

In [1]:
import pandas as pd

doc = []
with open('/Users/karenyang/Desktop/course4/dates.txt') as file:
    for line in file:
        doc.append(line)

df = pd.Series(doc)
df.head(10)

0         03/25/93 Total time of visit (in minutes):\n
1                       6/18/85 Primary Care Doctor:\n
2    sshe plans to move as of 7/8/71 In-Home Servic...
3                7 on 9/27/75 Audit C Score Current:\n
4    2/6/96 sleep studyPain Treatment Pain Level (N...
5                    .Per 7/06/79 Movement D/O note:\n
6    4, 5/18/78 Patient's thoughts about current su...
7    10/24/89 CPT Code: 90801 - Psychiatric Diagnos...
8                         3/7/86 SOS-10 Total Score:\n
9             (4/10/71)Score-1Audit C Score Current:\n
dtype: object

In [2]:
def date_sorter():
    
    # Your code here
    
    return # Your answer here

In [3]:
len(df)

500

In [4]:
for line in df:
    print(line)

03/25/93 Total time of visit (in minutes):

6/18/85 Primary Care Doctor:

sshe plans to move as of 7/8/71 In-Home Services: None

7 on 9/27/75 Audit C Score Current:

2/6/96 sleep studyPain Treatment Pain Level (Numeric Scale): 7

.Per 7/06/79 Movement D/O note:

4, 5/18/78 Patient's thoughts about current substance abuse:

10/24/89 CPT Code: 90801 - Psychiatric Diagnosis Interview

3/7/86 SOS-10 Total Score:

(4/10/71)Score-1Audit C Score Current:

(5/11/85) Crt-1.96, BUN-26; AST/ALT-16/22; WBC_12.6Activities of Daily Living (ADL) Bathing: Independent

4/09/75 SOS-10 Total Score:

8/01/98 Communication with referring physician?: Done

1/26/72 Communication with referring physician?: Not Done

5/24/1990 CPT Code: 90792: With medical services

1/25/2011 CPT Code: 90792: With medical services

4/12/82 Total time of visit (in minutes):

1; 10/13/1976 Audit C Score, Highest/Date:

4, 4/24/98 Relevant Drug History:

) 59 yo unemployed w referred by Urgent Care for psychiatric evaluation and follow up. The patient reports she has been dx w BAD. Her main complaint today is anergy. Ms. Hartman was evaluated on one occasion 5/21/77. She was a cooperative but somewhat vague historian.History of Present Illness and Precipitating Events

7/21/98 Total time of visit (in minutes):

210/21/79 SOS-10 Total Score:

3/03/90 CPT Code: 90792: With medical services

2/11/76 CPT Code: 90792: With medical services

07/25/1984 CPT Code: 90791: No medical services

4-13-82 Other Child Mental Health Outcomes Scales Used:

9/22/89 CPT Code: 90792: With medical services

9/02/76 CPT Code: 90791: No medical services

9/12/71 [report_end]

10/24/86 Communication with referring physician?: Done

03/31/1985 Total time of visit (in minutes):

7/20/72 CPT Code: 90791: No medical services

4/12/87= 1, negativeAudit C Score Current:

06/20/91 Total time of visit (in minutes):

5/12/2012 Primary Care Doctor:

3/15/83 SOS-10 Total Score:

2/14/73 CPT Code: 90801 - Psychiatric Diagnosis Interview

5/24/88 CPT Code: 90792: With medical services

7/27/1986 Total time of visit (in minutes):

1-14-81 Communication with referring physician?: Done

7-29-75 CPT Code: 90801 - Psychiatric Diagnosis Interview

(6/24/87) TSH-2.18; Activities of Daily Living (ADL) Bathing: Independent

8/14/94 Primary Care Doctor:

4/13/2002 Primary Care Doctor:

8/16/82 CPT Code: 90792: With medical services

2/15/1998 Total time of visit (in minutes):

7/15/91 CPT Code: 90792: With medical services

06/12/94 SOS-10 Total Score:

9/17/84 Communication with referring physician?: Done

2/28/75 Other Adult Mental Health Outcomes Scales Used:

sOP WPM - Dr. Romo-psychopharm since 11/22/75

"In the context of the patient's work up, she had Neuropsychological  testing 5/24/91.  She was referred because of her cognitive decline and symptoms of motor dysfunction to help characterize her current functioning. :

6/13/92 CPT Code: 90791: No medical services

7/11/71 SOS-10 Total Score:

12/26/86 CPT Code: 90791: No medical services

10/11/1987 CPT Code: 90791: No medical services

3/14/95 Primary Care Doctor:

12/01/73 CPT Code: 90791: No medical services

0: 12/5/2010 Audit C Score Current:

08/20/1982 SOS-10 Total Score:

7/24/95 SOS-10 Total Score:

8/06/83 CPT Code: 90791: No medical services

02/22/92 SOS-10 Total Score:

6/28/87 Impression Strengths/Abilities:

07/29/1994 CPT code: 99203

08/11/78 CPT Code: 90801 - Psychiatric Diagnosis Interview

10/29/91 Communication with referring physician?: Done

7/6/91 SOS-10 Total Score:

onone as of 1/21/87 Protective Factors:

24 yo right handed woman with history of large right frontal mass s/p resection 11/3/1985 who had recent urgent R cranial wound revision and placement of L EVD for declining vision and increased drainage from craniotomy incision site and possible infection. She has a hx of secondary mania related to psychosis and manipulation of her right frontal lobe.

7/04/82 CPT Code: 90801 - Psychiatric Diagnosis Interview

4-13-89 Communication with referring physician?: Not Done

Lithium 0.25 (7/11/77).  LFTS wnl.  Urine tox neg.  Serum tox + fluoxetine 500; otherwise neg.  TSH 3.28.  BUN/Cr: 16/0.83.  Lipids unremarkable.  B12 363, Folate >20.  CBC: 4.9/36/308 Pertinent Medical Review of Systems Constitutional:

4/12/74= 1Caffeine / Tobacco Use Caffeinated products: Yes

09/19/81 CPT Code: 90792: With medical services

9/6/79 Primary Care Doctor:

12/5/87 Total time of visit (in minutes):

01/05/1999 [report_end]

4/22/80 SOS-10 Total Score:

10/04/98 SOS-10 Total Score:

.Mr. Echeverria described having panic-like experiences on at least three occasions. The first of these episodes occurred when facial meshing was placed on him during radiation therapy. He recalled the experience vividly and described "freaking out", involving a sensation of crushing in his chest, difficulty breathing, a fear that he could die, and intense emotional disquiet. The second episode occurred during the last 10-15 minutes of an MRI scan. Mr. Echeverria noted feeling surprised and fearful when the feelings of panic started. Similar physiological and psychological symptoms were reported as above. The third episode occurred recently on 6/29/81. Mr.Echeverria was driving his car and felt similar symptoms as described above. He reported fearing that he would crash his vehicle and subsequently pulled over and abandoned his vehicle.

. Wile taking additional history, pt endorsed moderate depression and anxiety last 2 weeks, even though her period was on 8/04/78. Pt then acknowledged low to moderate mood and anxiety symptoms throughout the month, with premenstrual worsening. This mood pattern seems to have existed for many years, while premenstrual worsening increased in severity during last ~ 2 years, in context of likely peri menopause transition. Pt reported average of 3 hot flashes per day and 2 night sweats.

Death of mother; 7/07/1974 Meaningful activities/supports:

09/14/2000 CPT Code: 90792: With medical services

5/18/71 Total time of visit (in minutes):

8/09/1981 Communication with referring physician?: Done

6/05/93 CPT Code: 90791: No medical services

)Dilantin (PHENYTOIN) 100 MG CAPSULE Take 2 Capsule(s) PO HS; No Change (Taking Differently), Comments: decreased from 290 daily to 260 mg daily due to elevated phenytoin level from 8/9/97

12/8/82 Audit C=3Audit C Score Current:

8/26/89 CPT Code: 90791: No medical services

10/13/95 CPT Code: 90791: No medical services

4/19/91 Communication with referring physician?: Not Done

.APS - Psychiatry consult paged/requested in person at 04/08/2004 16:39 Patrick, Christian [hpp2]

9/20/76 CPT Code: 90801 - Psychiatric Diagnosis Interview

12/08/1990 @11 am [report_end]

4/11/1974 Chief Complaint / HPI Chief Complaint (Patients own words)

7/18/86 SOS-10 Total Score:

3/31/91 Communication with referring physician?: Done

5/13/72 Other Adult Mental Health Outcomes Scales Used:

011/14/83 Audit C Score Current:

8/16/92 SOS-10 Total Score:

10/05/97 CPT Code: 90791: No medical services

07/18/2002 CPT Code: 90792: With medical services

9/22/82 Total time of visit (in minutes):

2/24/74 SOS-10 Total Score:

(2/03/78) TSH-0.90 Activities of Daily Living (ADL) Bathing: Independent

2/11/2006 CPT Code: 90791: No medical services

Pt is a 21 year old, single, heterosexual identified, Liechtenstein male. He resides in Rabat, in a rented apartment, with a roommate. He has not graduated from high school nor has he earned his GED. He has been working full time, steadily, since the age of 16. He recently left a job at jacobs engineering group where he worked for about 5 years. He started working at becton dickinson a few weeks ago. Referral to SMH was precipitated by pt seeing his PCP, Dr. Ford, for a physical and sharing concerns re: depression. He was having suicidal thoughts the week of 8/22/83 and noticed that his depression and anxiety symptoms were starting to interfere with work. Per Dr. Ford's recommendation, he contacted PAL for assistance. When screened for substance use, pt was referred to SMH for an intake. Pt was scheduled to be seen last week due to urgency of his depression and SI, but missed the intake appointment due to getting extremely intoxicated the night before. Pt presents today seeking individual therapy and psychiatry services to address longstanding depression.

PET Scan (DPSH 5/04/74): 1) Marked hypometabolism involving the bilateral caudate nuclei. This is a non-specific finding, although this raises the question of a multisystem atrophy, specifically MSA-P (striatonigral degeneration), 2) Cortical hypometabolism involving the right inferior frontal gyrus. This is a non-specific finding of uncertain significance, and is not definitively related to a neurodegenerative process, although pathology in this region is not excluded

7/20/2011 [report_end]

6/17/95 Total time of visit (in minutes):

6/10/72 SOS-10 Total Score:

nPt denied use to me but endorsed use on 10/16/82 as part of BVH initial visit summary supplement by Nicholas BenjaminOpiates: Yes

12/15/92 CPT Code: 90801 - Psychiatric Diagnosis Interview

12/8/97 SOS-10 Total Score:

4/05/89 Primary Care Doctor:

12/04/87 SOS-10 Total Score:

4 (6/20/77)Audit C Score Current:

see 4/27/2006 consult note Dr. GuevaraWhat factors in prior treatment were helpful/not helpful:

07/17/92 CPT Code: 90791: No medical services

12/22/98 CPT Code: 90801 - Psychiatric Diagnosis Interview

10/02/96 Age:

11/05/90 CPT Code: 90792: With medical services

5/04/77 CPT Code: 90792: With medical services

2/27/96 Communication with referring physician?: Done

s The patient is a 44 year old married Caucasian woman, unemployed Decorator, living with husband and caring for two young children, who is referred by Capitol Hill Hospital PCP, Dr. Heather Zubia, for urgent evaluation/treatment till first visit with Dr. Toney Winkler IN EIGHT WEEKS on 24 Jan 2001.

.10 Sep 2004 - Intake at EEC for IOP but did not follow up

see above and APS eval of 26 May 1982 Social History Marital Status: Single

Tbooked for intake appointment at Sierra Vista, Chongging, WY on 28 June 2002

06 May 1972 SOS-10 Total Score:

25 Oct 1987 Total time of visit (in minutes):

14 Oct 1996 SOS-10 Total Score:

30 Nov 2007 CPT Code: 90801 - Psychiatric Diagnosis Interview

h missed intake office visit on 28 June 1994 at Sierra Vista Nursing HomeSuicidal Behavior Hx of Suicidal Behavior: Yes

14 Jan 1981 SOS-10 Total Score:

.On 10 Oct 1985 patient began FMLA from work.

11 February 1985 CPT Code: 90801 - Psychiatric Diagnosis Interview

7intake for follow up treatment at Anson General Hospital on 10 Feb 1983 @ 12 AM

s The patient is a 49 year old married Canadian emigree, living with husband and two young adult children, with history of recurrent major depression with psychotic features and SI/SA, and alcoholism, requiring multiple hospitalizations for SI/SA and detox, who presents for bridge care s/p discharge from Placerville Sanatorium on 05 Feb 1992 and follow up outpatient mental health treatment at Anson General Hospital.

ssee 21 Oct 2012 Schroder Hospital discharge summaryPsychiatric Review of Systems DEPRESSION: Has the patient had periods of time lasting two weeks or longer in which, most of the day on most days, they felt little interest or pleasure in doing things, or they had to push themselves to do things: Yes

14 Feb 1995 Primary Care Doctor:

30 May 2016 SOS-10 Total Score:

22 Jan 1996 @ 11 AMCommunication with referring physician?: Done

14 Oct 1992 CPT Code: 90792: With medical services

.On 06 Oct 2003 patient sought attention of CMC PCP Dr. Nevarez, who consulted  Grandview Sanitarium, obrained consultation from this psychiatrist, who considered SSRI 'poop out' and suggested swtich from paroxitine to fluoxetine.

18 Oct 1999 SOS-10 Total Score:

11 Nov 2004 Total time of visit (in minutes):

30 May 2001 CPT Code: 90801 - Psychiatric Diagnosis Interview

.On 02 Feb 1978 patient was seen by Dr. Fisher who found depression had relapsed on fluoxetine 20 mg, with patient reporting work-related stressors and complaining "Prozac has stopped working".  Plan:  stop fluoxetine and start bupropion 150 mg BID.

09 Sep 1989 Primary Care Doctor:

12 March 1980 SOS-10 Total Score:

22 June 1990 Medical History:

28 Sep 2015 Primary Care Doctor:

13 Jan 1972 Primary Care Doctor:

06 Mar 1974 Primary Care Doctor:

10 Oct 1974 Primary Care Doctor:

26 May 1974 Primary Care Doctor:

short term partial hospital program at Pine Rest Hospital starting 10 Feb 1990

23 Aug 2000 Primary Care Doctor:

.The patient brought himself to APS on 26 May 2001 for ONE MONTH HISTORY of recurrence of increased depressed and anxious mood, with

see 21 Oct 2007 Schroder Hospital discharge summaryViolent Behavior Hx of Violent Behavior: Yes

19 Oct 2016 Communication with referring physician?: Done

dON 05 Mar 1974

29 Jan 1994 Primary Care Doctor:

see 21 Oct 1978 Schroder Hospital discharge summaryHx of Non Suicidal Self Injurious Behavior: Yes

.On 18 August 1975 patient presented to BH ED/APS for psychological distress over binge eating and weight concerns, as well as acknowledging chronic intermittent SI but no acute SI; otherwise good response to Abilify 20 mg QD.  Patient was discharged home to follow up with Urgent care TODAY.

11 Nov 1996 CPT Code: 90792: With medical services

01 Oct 1979 Primary Care Doctor:

.On 13 Oct 1986 patient admitted to Schroder Hospital for affect instability, having been discharged THAT DAY from a residential program.

see 21 Oct 1995 Schroder Hospital discharge summary-Psychiatric History Hx of Inpatient Treatment: Yes

44 y/o MWF, unemployed Decorator, living with husband and caring for their two young children, referred by CHH PCP for urgent evaluation/treatment till first visit with Dr. Toney Winkler on 24 Jan 2011, presents with history of unclear rheumatologic illness and partially treated post-partum depression which has worsened in severity since patient's discovery of dire family financial situation, with significant anxiety symptoms causing insomnia.

04 Oct 1972 Total time of visit (in minutes):

.On 23 Aug 1993 at return office visit Dr. Fisher found patient to still be depressed on bupropion 150 mg QD, with new complaints of cognitive symptoms: "difficult to speak in an organized fashion, has poor memory, and has some word finding difficulties".  Patient reports cognitive problems as "can't find the right word....can't remember how to say the word".  Brain MR was WNL.

18 Oct 2006 Age:

.On 04 Dec 1988 the patient was admitted to Fairmont Hospital from the APS for NINE MONTH history of increased depression severity, on treatment with sertraline 200 mg, Lunesta 3 mg, and lorazepam 0.5 mg 1-2 QD prn, and in midst of SIX MONTH trial of psychotherapy from Carol Shaw, PhD, in the setting of termination from job as User Support Technician, after six month leave, in midst of lawsuit over wrongful termination.

.On 21 Oct 1983 patient was discharged from Scroder Hospital after EIGHT DAY ADMISSION

see above and APS eval of 26 May 2010 Education Education Level: College Grad

22 year old single Caucasian/Latino woman, unemployed Cook recent college graduate, living along with pet rabbit, with long history of depression with cutting and SA but never hospitalized, as well as obesity, hypothyroidism in euthyroid state and PCO, referred by new NMH PCP Dr. Evelyn Julian for urgent evaluation and treatment till first visit with colleague, Dr.  Inez Burns, on 18 Jan 1990, presents with untreated recurrent major depression and developmental history of verbally abusive alcohol abusing mother and school bullying.

15 Jun 1985 @ 11 AMCommunication with referring physician?: Done

.On 10 Dec 1982, the first night after hospital discharge, the patient experienced a nightmare, which he attributed to new medications and he self-discontinued all these new medications.

.On 09 Dec 1988 the patient was discharged home-

18 August 1995 Primary Care Doctor:

eby 13 June 1974 it appears amitriptyline had been stopped and bupropion 150 mg BID was restarted.

see above and APS eval of 26 May 2008 Financial Stress: Yes

11 Nov 2002 SOS-10 Total Score:

see 17 Aug 1985 eval by Dr. Ngo.Social History Marital Status: Married

13 Oct 2016 Primary Care Doctor:

14 Jan 2008 Total time of visit (in minutes):

12 March 2004 CPT Code: 90801 - Psychiatric Diagnosis Interview

ssee 21 Oct 1977 Schroder Hospital discharge summaryHx of Outpatient Treatment: Yes

.By 10 Aug 2000 patient was rehospitalized at Sweetwater Hospital for depression, SI, hypersomnia, fatigue, poor concentration, negative ruminations, dissociated states and ? VH.  This was in the setting of no medications and continued alcohol and MJ abuse.

30 Nov 1972 SOS-10 Total Score:

06 May 1993 CPT Code: 90792: With medical services

s 22 year old single Caucasian/Latino woman, unemployed Cook recent college graduate, living along with pet rabbit, with long history of depression with SA but never hospitalized, as well as obesity, hypothyroidism, and PCO, referred by new NMH PCP Dr. Evelyn Julian for urgent evaluation and treatment till first visit with colleague, Dr.  Inez Burns, on 18 Jan 1995.

April 11, 1990 CPT Code: 90791: No medical services

MRI May 30, 2001 empty sella but no problems with endocrine functionPertinent Medical Review of Systems Constitutional:

.Feb 18, 1994: made a phone call to Mom and Mom commented that he was talking very fast, hard to interrupt, but was in super happy spirits, so didn't make a big deal of it.

Brother died February 18, 1981 Parental/Caregiver obligations:

none; but currently has appt with new HJH PCP Rachel Salas, MD on October. 11, 2013 Other Agency Involvement: No

.Came back to US on Jan 24 1986, saw Dr. Quackenbush at Beaufort Memorial Hospital.  Checked VPA level and found it to be therapeutic and confirmed BPAD dx.  Also, has a general physician exam and found to be in good general health, except for being slightly overwt.

July 26, 1978 Total time of visit (in minutes):

father was depressed inpatient at DFC December 23, 1999 Family History of Substance Abuse: Yes

May 15, 1989 SOS-10 Total Score:

September 06, 1995 Total time of visit (in minutes):

Mar. 10, 1976 CPT Code: 90791: No medical services

.Got back to U.S. Jan 27, 1983.

Queen Hamilton in Bonita Springs courthouse.  Ends October 23 1990 Current legal stresses/needs:

r August 12 2004 - diagnosed with Parkinson's stopped working Financial Stress: No

September 01, 2012 Age:

July 25, 1983 Total time of visit (in minutes):

August 11, 1989 Total time of visit (in minutes):

April 17, 1992 Total time of visit (in minutes):

EKG July 24, 1999: QTc 496 msPertinent Medical Review of Systems Constitutional:

July 11, 1997 CPT Code: 90792: With medical services

s Gale Youngquist is a 22 yo single Caucasian female who presents to the HJH Psychiatry for an evaluation of her current eating disorder status and treatment needs.  She shared that she began restricting at age 11 yo but could not identify any specific triggers.  "Mostly I wouldn't eat at school, and then I'd have dinner at home, but some days not," per pt. Her parents and ski coach started noticing that "I wasn't eating and was losing weight."  She began outpatient treatment at age 11, and has been in and out of outpatient and higher levels of care since then, including multiple emergency room visits and against medical advice (AMA) departures.  Most recently, she left Jefferson County Health Delegates AMA on Sep. 10, 1974.  "They weren't saying I was ready to go, but insurance pulled out," per pt.  She said she felt both dissappointed but also relieved to leave residential care to move back home w/ her mother.

.August 14, 1981- bad reaction to SpiceK2 - synthetic MJ- admitted to Crete Manor, Mcalester.

Nov 11, 1988 Total time of visit (in minutes):

e June 13, 2011 Suicidal Behavior Hx of Suicidal Behavior: Uncertain


In [5]:
# index position of date errors
list_errors = [265,271,235,245,256,281,283,285,333,459,460,461,465,467,468,479,487,488,490,298,313,321,274,21]

In [7]:
import re

In [8]:
df[[21]] = re.sub(r'210/21/79', '10/21/79', df[21])
df[21]

'10/21/79 SOS-10 Total Score:\n'

In [9]:
df[[235]] = re.sub(r'pOct 2015', 'Oct 2015', df[235])
df[235]

'Oct 2015 - Admitted to Gray Clinic for depression, alcohol intox/dependence and SI.  Discharged to MH Partial Hospital---on trazadone 50 mg QHS, Ativan 0.5 mg BID, Wellbutrin 150 mg BID, Seroquel 50 mg QHS and Zoloft 100 mg.  It is unclear if patient attended Memorial partial hospital program.  By report she had refills of trazadone and sertraline via PCP (see HPI).Hx of Outpatient Treatment: Yes\n'

In [10]:
df[[245]] = re.sub(r'lNovember 1990', '01 November 1990', df[245])
df[245]

'01 November 1990 - NPCCHx of Outpatient Treatment: Yes\n'

In [11]:
df[[256]] = re.sub(r'IAug 1988', 'Aug 1988', df[256])
df[256]

'Aug 1988: Symmes Hospital s/p SA OD with ASA\n'

In [12]:
df[[265]] = re.sub(r'/', '', df[265])
df[265]

'.  Pt reports ho difficulty with EtOH and opioids. EtOH: 1st use at age 10, regular use beginning in high school, more problematic at age 25 when started losing things.  Drinking 12 beersday over past year since returning to State College from Alaska.  Unsure of heaviest use period.  ho frequent blackouts.  Has passed out and woken up in variety of places.  ho withdrawal symptoms, 1st detox at age 25, no ho withdrawal seizure, no DTs.  opioids: 1st use at age 21 (perocet).  Began using daily at age 25, at worst was using 8 to 10 percocets per day (depending on dose).  Detox in April 1989, was using perioidically since back in State College, but has primarily been drinking.  Last use 3 mths ago.  no ho suboxone or methadone.  No ho accidental OD.  No ho heroin use.  No ho IVDU.  tobacco: 1 ppd since age 16, some interest in quitting, not right now.  Ho quitting for a week.\n'

In [13]:
df[[271]] = re.sub(r'708-810-7787 ', '', df[271])
df[271]

'.Spoke to sister Naomi Ely who reports he has been doing much better since he went to Dysart Clinic (he was drinking for a month leading up to this, his ammonia was high, and physicians were worried about early).  She feels his cognition is back to baseline, "100% better".  She says he has been successful in abstaining from substances as far as she knows, thinks a schedule is useful to him, doctor\'s appts etc.  Notes that he returned from LA in August 2008, gets bouts of "exhaustion" even in sobriety.  She denies ever witnessing any periods of manic behavior from patient.  Their father has dementia that started at age 84.  Notes patient is living with uncle in Black River Falls (uncle is 89), lived with sister 3 months who also takes care of her own father in Talladega.  She knows he is working on getting social security, subsidizing housing.  Stable situation with patient\'s girlfriend Nutt.Suicidal Behavior Hx of Suicidal Behavior: No\n'

In [14]:
df[[274]] = re.sub(r'7HH, April 1985', 'April 1985', df[274])
df[274]

'April 1985 Hx of Outpatient Treatment:\n'

In [15]:
df[[281]] = re.sub(r'yAug 2004', 'Aug 2004', df[281])
df[281]

'Aug 2004 - Dr. Tom Ngo at TMC; dx GAD; patient stopped after two visits re: "I was scared if this meant I was sick and really needed this", despite success in controlling anxiety-related symptoms of nausea after just one treatment visit.Psychiatric Review of Systems DEPRESSION: Has the patient had periods of time lasting two weeks or longer in which, most of the day on most days, they felt little interest or pleasure in doing things, or they had to push themselves to do things: No\n'

In [16]:
df[[284]] = re.sub(r'- Jan 1987', 'Jan 1987', df[284])
df[284]

'.  Alvarado Medical Center Jan 1987 : worsening psychosis and mania (impulsivity of going to Pompeii, grandiosity in wanting to send script to famous playwright, increased painting activity, maxed out credit card, decreased sleep) Hx of Outpatient Treatment: Yes\n'

In [17]:
df[[285]] = re.sub(r'sSep 1983 GSW', 'Sep 1983 GSW', df[285])
df[285]

'Sep 1983 GSW to face (L-TMJ region), ? gang related, with L-CN VII injury and ? TBI, requiring plastic surgical reconstructionActivities of Daily Living (ADL) Bathing: Independent\n'

In [18]:
df[[333]] = re.sub(r'sNovember 1997', 'November 1997', df[333])
df[333]

'November 1997 - suicidal ideation - HHR\n'

In [19]:
df[[460]] = re.sub(r'1 Ex-smoker : quit 2012', 'Ex-smoker : quit 2012 ', df[460])
df[460]

'Ex-smoker : quit 2012 \n'

In [20]:
df[[461]] = re.sub(r'. Age 16, 1991,', '1991', df[461])
df[461]

'1991 frontal impact. out for two weeks from sports.\n'

In [21]:
df[[462]] = re.sub(r'sLexapro (1988-now): Good response (anxiety)', '1988', df[462])
df[462]

'sLexapro (1988-now): Good response (anxiety)\n'

In [22]:
df[[465]] = re.sub(r'.Age, 19, 1976, ', '1976 ', df[465])
df[465]

'1976 playing football, frontal impact. out for two weeks from sports.\n'

In [23]:
df[[466]] = re.sub(r's1981 ', '1981 ', df[466])
df[466]

'1981  Swedish-American Hospital\n'

In [24]:
df[[467]] = re.sub(r'aS/P ', '', df[467])
df[467]

'suicide attempt 2011 Hx of Outpatient Treatment: Yes\n'

In [25]:
df[[479]] = re.sub(r'(1993)', '1993', df[479])
df[479]

'sIn KEP Psychiatryfor therapy and medications since 1996 Prior medication trials (including efficacy, reasons discontinued):\n'

In [26]:
df[[487]] = re.sub(r'appendectomy s/p delivery 1992', '1992', df[487])
df[487]

'1992 Prior relevant labs:\n'

In [27]:
df[[488]] = re.sub(r': s/p nephrectomy 1977', '1977', df[488])
df[488]

'tProblems renal cell cancer 1977\n'

In [28]:
df[[490]] = re.sub(r'Lab: B12 969 2007', '2007 ', df[490])
df[490]

'2007 \n'

In [ ]:
# Write expressions for group of same data format

In [29]:
expression1 = r'\d{,2}[/-]\d{,2}[/-]\d{2,4}'

In [30]:
# test cases for expression1
line0 = "09/14/2000 CPT Code: 90792: With medical services"
line1 = "sOP WPM - Dr. Romo-psychopharm since 11/22/75"
line2 = "4-13-82 Other Child Mental Health Outcomes Scales Used:"
line3 = "Dilantin (PHENYTOIN) 100 MG CAPSULE Take 2 Capsule(s) PO HS; No Change (Taking Differently), \
Comments: decreased from 290 daily to 260 mg daily due to elevated phenytoin level from 8/9/97"
line4 = "PET Scan (DPSH 5/04/74): 1)"

In [31]:
result0 = re.findall(expression1, line0)
result1 = re.findall(expression1, line1)
result2 = re.findall(expression1, line2)
result3 = re.findall(expression1, line3)
result4 = re.findall(expression1, line4)

In [32]:
print(result0)
print(result1)
print(result2)
print(result3)
print(result4)

['09/14/2000']
['11/22/75']
['4-13-82']
['8/9/97']
['5/04/74']

In [33]:
expression1 = r'\d{,2}[/-]\d{,2}[/-]\d{2,4}'

list1 = []
for line in df[0:125]:
    
    result1 = re.findall(expression1, line)
    if result1 != []:
        list1.append(result1[0])
print(list1)

['03/25/93', '6/18/85', '7/8/71', '9/27/75', '2/6/96', '7/06/79', '5/18/78', '10/24/89', '3/7/86', '4/10/71', '5/11/85', '4/09/75', '8/01/98', '1/26/72', '5/24/1990', '1/25/2011', '4/12/82', '10/13/1976', '4/24/98', '5/21/77', '7/21/98', '10/21/79', '3/03/90', '2/11/76', '07/25/1984', '4-13-82', '9/22/89', '9/02/76', '9/12/71', '10/24/86', '03/31/1985', '7/20/72', '4/12/87', '06/20/91', '5/12/2012', '3/15/83', '2/14/73', '5/24/88', '7/27/1986', '1-14-81', '7-29-75', '6/24/87', '8/14/94', '4/13/2002', '8/16/82', '2/15/1998', '7/15/91', '06/12/94', '9/17/84', '2/28/75', '11/22/75', '5/24/91', '6/13/92', '7/11/71', '12/26/86', '10/11/1987', '3/14/95', '12/01/73', '12/5/2010', '08/20/1982', '7/24/95', '8/06/83', '02/22/92', '6/28/87', '07/29/1994', '08/11/78', '10/29/91', '7/6/91', '1/21/87', '11/3/1985', '7/04/82', '4-13-89', '7/11/77', '4/12/74', '09/19/81', '9/6/79', '12/5/87', '01/05/1999', '4/22/80', '10/04/98', '6/29/81', '8/04/78', '7/07/1974', '09/14/2000', '5/18/71', '8/09/1981', '6/05/93', '8/9/97', '12/8/82', '8/26/89', '10/13/95', '4/19/91', '04/08/2004', '9/20/76', '12/08/1990', '4/11/1974', '7/18/86', '3/31/91', '5/13/72', '11/14/83', '8/16/92', '10/05/97', '07/18/2002', '9/22/82', '2/24/74', '2/03/78', '2/11/2006', '8/22/83', '5/04/74', '7/20/2011', '6/17/95', '6/10/72', '10/16/82', '12/15/92', '12/8/97', '4/05/89', '12/04/87', '6/20/77', '4/27/2006', '07/17/92', '12/22/98', '10/02/96', '11/05/90', '5/04/77', '2/27/96']

In [34]:
len(df[0:125])

125

In [35]:
from dateutil.parser import parse
lista = []

for item in list1:
    a = str(parse(item , dayfirst=False))
    lista.append(a)
    
print(lista)

['1993-03-25 00:00:00', '1985-06-18 00:00:00', '1971-07-08 00:00:00', '1975-09-27 00:00:00', '1996-02-06 00:00:00', '1979-07-06 00:00:00', '1978-05-18 00:00:00', '1989-10-24 00:00:00', '1986-03-07 00:00:00', '1971-04-10 00:00:00', '1985-05-11 00:00:00', '1975-04-09 00:00:00', '1998-08-01 00:00:00', '1972-01-26 00:00:00', '1990-05-24 00:00:00', '2011-01-25 00:00:00', '1982-04-12 00:00:00', '1976-10-13 00:00:00', '1998-04-24 00:00:00', '1977-05-21 00:00:00', '1998-07-21 00:00:00', '1979-10-21 00:00:00', '1990-03-03 00:00:00', '1976-02-11 00:00:00', '1984-07-25 00:00:00', '1982-04-13 00:00:00', '1989-09-22 00:00:00', '1976-09-02 00:00:00', '1971-09-12 00:00:00', '1986-10-24 00:00:00', '1985-03-31 00:00:00', '1972-07-20 00:00:00', '1987-04-12 00:00:00', '1991-06-20 00:00:00', '2012-05-12 00:00:00', '1983-03-15 00:00:00', '1973-02-14 00:00:00', '1988-05-24 00:00:00', '1986-07-27 00:00:00', '1981-01-14 00:00:00', '1975-07-29 00:00:00', '1987-06-24 00:00:00', '1994-08-14 00:00:00', '2002-04-13 00:00:00', '1982-08-16 00:00:00', '1998-02-15 00:00:00', '1991-07-15 00:00:00', '1994-06-12 00:00:00', '1984-09-17 00:00:00', '1975-02-28 00:00:00', '1975-11-22 00:00:00', '1991-05-24 00:00:00', '1992-06-13 00:00:00', '1971-07-11 00:00:00', '1986-12-26 00:00:00', '1987-10-11 00:00:00', '1995-03-14 00:00:00', '1973-12-01 00:00:00', '2010-12-05 00:00:00', '1982-08-20 00:00:00', '1995-07-24 00:00:00', '1983-08-06 00:00:00', '1992-02-22 00:00:00', '1987-06-28 00:00:00', '1994-07-29 00:00:00', '1978-08-11 00:00:00', '1991-10-29 00:00:00', '1991-07-06 00:00:00', '1987-01-21 00:00:00', '1985-11-03 00:00:00', '1982-07-04 00:00:00', '1989-04-13 00:00:00', '1977-07-11 00:00:00', '1974-04-12 00:00:00', '1981-09-19 00:00:00', '1979-09-06 00:00:00', '1987-12-05 00:00:00', '1999-01-05 00:00:00', '1980-04-22 00:00:00', '1998-10-04 00:00:00', '1981-06-29 00:00:00', '1978-08-04 00:00:00', '1974-07-07 00:00:00', '2000-09-14 00:00:00', '1971-05-18 00:00:00', '1981-08-09 00:00:00', '1993-06-05 00:00:00', '1997-08-09 00:00:00', '1982-12-08 00:00:00', '1989-08-26 00:00:00', '1995-10-13 00:00:00', '1991-04-19 00:00:00', '2004-04-08 00:00:00', '1976-09-20 00:00:00', '1990-12-08 00:00:00', '1974-04-11 00:00:00', '1986-07-18 00:00:00', '1991-03-31 00:00:00', '1972-05-13 00:00:00', '1983-11-14 00:00:00', '1992-08-16 00:00:00', '1997-10-05 00:00:00', '2002-07-18 00:00:00', '1982-09-22 00:00:00', '1974-02-24 00:00:00', '1978-02-03 00:00:00', '2006-02-11 00:00:00', '1983-08-22 00:00:00', '1974-05-04 00:00:00', '2011-07-20 00:00:00', '1995-06-17 00:00:00', '1972-06-10 00:00:00', '1982-10-16 00:00:00', '1992-12-15 00:00:00', '1997-12-08 00:00:00', '1989-04-05 00:00:00', '1987-12-04 00:00:00', '1977-06-20 00:00:00', '2006-04-27 00:00:00', '1992-07-17 00:00:00', '1998-12-22 00:00:00', '1996-10-02 00:00:00', '1990-11-05 00:00:00', '1977-05-04 00:00:00', '1996-02-27 00:00:00']

In [36]:
len(lista)

125

In [37]:
expression2 = r'(?:\d{0,2} )?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,\s]* (?:\d{ ,2}, )?\d{4}'
expression3 = r'(?:\d{0,2} )?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,]* \d{0,2}[,.\s]*\d{2,4}'

In [38]:
# test cases for expression2 and expression3
line4 = ".On 21 Oct 1983 patient was discharged from Scroder Hospital after EIGHT DAY ADMISSION"
line5 = "11 February 1985 CPT Code: 90801 - Psychiatric Diagnosis Interview"
line6 = "19 Oct 2016 Communication with referring physician?: Done"
line7 = "20 March, 2009"
line8 = "20 Mar. 2009"
line9 = "06 May 1972 SOS-10 Total Score:"
line10 = "24 Jan 2001"
line11 = "May, 2011"
line12 = "August 12 2004"

In [39]:
result4 = re.findall(expression2, line4)
result5 = re.findall(expression3, line5)
result6 = re.findall(expression3, line6)
result7 = re.findall(expression2, line7)
result8 = re.findall(expression2, line8)
result9 = re.findall(expression2, line9)
result10 = re.findall(expression2, line10)
result11 = re.findall(expression3, line11)
result12 = re.findall(expression3, line12)

In [40]:
print(result4)
print(result5)
print(result6)
print(result7)
print(result8)
print(result9)
print(result10)
print(result11)
print(result12)

['21 Oct 1983']
['11 February 1985']
['19 Oct 2016']
['20 March, 2009']
['20 Mar. 2009']
['06 May 1972']
['24 Jan 2001']
['May, 2011']
['August 12 2004']

In [41]:
expression2 = r'(?:\d{0,2} )?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,\s]* (?:\d{ ,2}, )?\d{4}'
expression3 = r'(?:\d{0,2} )?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,]* \d{0,2}[,.\s]*\d{2,4}'

list2 = []
for line in df[125:228]:
    
    result2 = re.findall(expression2, line)
    if result2 != []:
        list2.append(result2[0])
    else:
        result2 = re.findall(expression3, line)
        list2.append(result2[0])
        
print(list2)

['24 Jan 2001', '10 Sep 2004', '26 May 1982', '28 June 2002', '06 May 1972', '25 Oct 1987', '14 Oct 1996', '30 Nov 2007', '28 June 1994', '14 Jan 1981', '10 Oct 1985', '11 February 1985', '10 Feb 1983', '05 Feb 1992', '21 Oct 2012', '14 Feb 1995', '30 May 2016', '22 Jan 1996', '14 Oct 1992', '06 Oct 2003', '18 Oct 1999', '11 Nov 2004', '30 May 2001', '02 Feb 1978', '09 Sep 1989', '12 March 1980', '22 June 1990', '28 Sep 2015', '13 Jan 1972', '06 Mar 1974', '10 Oct 1974', '26 May 1974', '10 Feb 1990', '23 Aug 2000', '26 May 2001', '21 Oct 2007', '19 Oct 2016', '05 Mar 1974', '29 Jan 1994', '21 Oct 1978', '18 August 1975', '11 Nov 1996', '01 Oct 1979', '13 Oct 1986', '21 Oct 1995', '24 Jan 2011', '04 Oct 1972', '23 Aug 1993', '18 Oct 2006', '04 Dec 1988', '21 Oct 1983', '26 May 2010', '18 Jan 1990', '15 Jun 1985', '10 Dec 1982', '09 Dec 1988', '18 August 1995', '13 June 1974', '26 May 2008', '11 Nov 2002', '17 Aug 1985', '13 Oct 2016', '14 Jan 2008', '12 March 2004', '21 Oct 1977', '10 Aug 2000', '30 Nov 1972', '06 May 1993', '18 Jan 1995', 'April 11, 1990', ' May 30, 2001', 'Feb 18, 1994', ' February 18, 1981', ' October. 11, 2013', ' Jan 24 1986', 'July 26, 1978', ' December 23, 1999', 'May 15, 1989', 'September 06, 1995', 'Mar. 10, 1976', ' Jan 27, 1983', ' October 23 1990', ' August 12 2004', 'September 01, 2012', 'July 25, 1983', 'August 11, 1989', 'April 17, 1992', ' July 24, 1999', 'July 11, 1997', ' Sep. 10, 1974', 'August 14, 1981', 'Nov 11, 1988', ' June 13, 2011', 'May 14, 1989', ' Dec 14 1975', ' June 25, 2012', 'Oct 18, 1980', 'May 15, 1998', ' October 14 1974', 'July 25, 1998', 'June 15, 1972', ' January 07, 1991', 'September. 15, 2011']

In [42]:
len(df[125:228])

103

In [43]:
len(list2)

103

In [44]:
from dateutil.parser import parse
listb = []

for item in list2:
    b = str(parse(item, dayfirst=False))
    listb.append(b)
    
print(listb)

['2001-01-24 00:00:00', '2004-09-10 00:00:00', '1982-05-26 00:00:00', '2002-06-28 00:00:00', '1972-05-06 00:00:00', '1987-10-25 00:00:00', '1996-10-14 00:00:00', '2007-11-30 00:00:00', '1994-06-28 00:00:00', '1981-01-14 00:00:00', '1985-10-10 00:00:00', '1985-02-11 00:00:00', '1983-02-10 00:00:00', '1992-02-05 00:00:00', '2012-10-21 00:00:00', '1995-02-14 00:00:00', '2016-05-30 00:00:00', '1996-01-22 00:00:00', '1992-10-14 00:00:00', '2003-10-06 00:00:00', '1999-10-18 00:00:00', '2004-11-11 00:00:00', '2001-05-30 00:00:00', '1978-02-02 00:00:00', '1989-09-09 00:00:00', '1980-03-12 00:00:00', '1990-06-22 00:00:00', '2015-09-28 00:00:00', '1972-01-13 00:00:00', '1974-03-06 00:00:00', '1974-10-10 00:00:00', '1974-05-26 00:00:00', '1990-02-10 00:00:00', '2000-08-23 00:00:00', '2001-05-26 00:00:00', '2007-10-21 00:00:00', '2016-10-19 00:00:00', '1974-03-05 00:00:00', '1994-01-29 00:00:00', '1978-10-21 00:00:00', '1975-08-18 00:00:00', '1996-11-11 00:00:00', '1979-10-01 00:00:00', '1986-10-13 00:00:00', '1995-10-21 00:00:00', '2011-01-24 00:00:00', '1972-10-04 00:00:00', '1993-08-23 00:00:00', '2006-10-18 00:00:00', '1988-12-04 00:00:00', '1983-10-21 00:00:00', '2010-05-26 00:00:00', '1990-01-18 00:00:00', '1985-06-15 00:00:00', '1982-12-10 00:00:00', '1988-12-09 00:00:00', '1995-08-18 00:00:00', '1974-06-13 00:00:00', '2008-05-26 00:00:00', '2002-11-11 00:00:00', '1985-08-17 00:00:00', '2016-10-13 00:00:00', '2008-01-14 00:00:00', '2004-03-12 00:00:00', '1977-10-21 00:00:00', '2000-08-10 00:00:00', '1972-11-30 00:00:00', '1993-05-06 00:00:00', '1995-01-18 00:00:00', '1990-04-11 00:00:00', '2001-05-30 00:00:00', '1994-02-18 00:00:00', '1981-02-18 00:00:00', '2013-10-11 00:00:00', '1986-01-24 00:00:00', '1978-07-26 00:00:00', '1999-12-23 00:00:00', '1989-05-15 00:00:00', '1995-09-06 00:00:00', '1976-03-10 00:00:00', '1983-01-27 00:00:00', '1990-10-23 00:00:00', '2004-08-12 00:00:00', '2012-09-01 00:00:00', '1983-07-25 00:00:00', '1989-08-11 00:00:00', '1992-04-17 00:00:00', '1999-07-24 00:00:00', '1997-07-11 00:00:00', '1974-09-10 00:00:00', '1981-08-14 00:00:00', '1988-11-11 00:00:00', '2011-06-13 00:00:00', '1989-05-14 00:00:00', '1975-12-14 00:00:00', '2012-06-25 00:00:00', '1980-10-18 00:00:00', '1998-05-15 00:00:00', '1974-10-14 00:00:00', '1998-07-25 00:00:00', '1972-06-15 00:00:00', '1991-01-07 00:00:00', '2011-09-15 00:00:00']

In [45]:
len(listb)

103

In [46]:
expression4 = r'(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,]* (?:\d{ ,2}, )?\d{4}'

In [47]:
# test case for expression4
line13 = ".Nov 2007- Evaluation and treatment at CH ED/APS for acute alcohol and medication OD,"

In [48]:
result13 = re.findall(expression4, line13)

In [49]:
print(result13)

['Nov 2007']

In [50]:
expression4 = r'(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,]* (?:\d{ ,2}, )?\d{4}'
              
list4 = []
for line in df[228:321]:
    
    result4 = re.findall(expression4, line)
    if result4 != []:
        list4.append(result4[0])
    # correct misspellings for 'Decemeber 1978' and 'Janaury 1993'
list4[-8] = "December 1978"
list4[-23] = 'January 1993'
    
print(list4)

['September 1985', 'June 2011', 'May 1986', 'May 2016', 'July 1977', 'July, 1990', 'Jul 2003', 'Oct 2015', 'May 1995', 'February 1976', 'January 1995', 'Feb 1978', 'May, 2011', 'May 2004', 'Nov 2010', 'Sep 2012', 'January, 2013', 'November 1990', 'July 1981', 'May 1983', 'July 1995', 'April 1993', 'May 2005', 'December 1998', 'Jan 2007', 'Feb 2016', 'August 1979', 'Oct 2014', 'Aug 1988', 'Sep 2015', 'Apr 1976', 'Nov 1979', 'February 2000', 'Oct 1986', 'Jun 2002', 'September 1981', 'June 2007', 'April 1989', 'September 1999', 'Oct 1980', 'Dec 2009', 'July 1992', 'May, 2006', 'August 2008', 'Feb 1993', 'February, 2010', 'April 1985', 'September 1984', 'April 1986', 'Apr 2007', 'September 1974', 'Sep 2013', 'July 1985', 'Aug 2004', 'May 2012', 'Feb 1977', 'Jan 1987', 'Sep 1983', 'January 2013', 'Mar 2010', 'August 2009', 'Sep 2007', 'December 2011', 'Jan 2004', 'November 1995', 'September 2008', 'February 1983', 'March 1983', 'Aug 1979', 'Jan 2009', 'January 1993', 'March 1974', 'January 1994', 'Dec 1992', 'November 2004', 'January 1977', 'Mar 2002', 'Feb 2000', 'May, 2004', 'July 2006', 'Feb 1994', 'April 1977', 'Oct 1992', 'February, 1995', 'February 1989', 'December 1978', 'January 2007', 'Jun 1976', 'May 2011', 'Mar, 1975', 'Jan 1978', 'July 1975', 'November 2012']

In [51]:
len(df[228:321])

93

In [52]:
len(list4)

93

In [53]:
list44 = []
for item in list4:
    x = "01 " + item
    list44.append(x)

print(list44)

['01 September 1985', '01 June 2011', '01 May 1986', '01 May 2016', '01 July 1977', '01 July, 1990', '01 Jul 2003', '01 Oct 2015', '01 May 1995', '01 February 1976', '01 January 1995', '01 Feb 1978', '01 May, 2011', '01 May 2004', '01 Nov 2010', '01 Sep 2012', '01 January, 2013', '01 November 1990', '01 July 1981', '01 May 1983', '01 July 1995', '01 April 1993', '01 May 2005', '01 December 1998', '01 Jan 2007', '01 Feb 2016', '01 August 1979', '01 Oct 2014', '01 Aug 1988', '01 Sep 2015', '01 Apr 1976', '01 Nov 1979', '01 February 2000', '01 Oct 1986', '01 Jun 2002', '01 September 1981', '01 June 2007', '01 April 1989', '01 September 1999', '01 Oct 1980', '01 Dec 2009', '01 July 1992', '01 May, 2006', '01 August 2008', '01 Feb 1993', '01 February, 2010', '01 April 1985', '01 September 1984', '01 April 1986', '01 Apr 2007', '01 September 1974', '01 Sep 2013', '01 July 1985', '01 Aug 2004', '01 May 2012', '01 Feb 1977', '01 Jan 1987', '01 Sep 1983', '01 January 2013', '01 Mar 2010', '01 August 2009', '01 Sep 2007', '01 December 2011', '01 Jan 2004', '01 November 1995', '01 September 2008', '01 February 1983', '01 March 1983', '01 Aug 1979', '01 Jan 2009', '01 January 1993', '01 March 1974', '01 January 1994', '01 Dec 1992', '01 November 2004', '01 January 1977', '01 Mar 2002', '01 Feb 2000', '01 May, 2004', '01 July 2006', '01 Feb 1994', '01 April 1977', '01 Oct 1992', '01 February, 1995', '01 February 1989', '01 December 1978', '01 January 2007', '01 Jun 1976', '01 May 2011', '01 Mar, 1975', '01 Jan 1978', '01 July 1975', '01 November 2012']

In [54]:
len(list44)

93

In [55]:
listc = []

for item in list44:
    c = str(parse(item, dayfirst=False))
    print(c)
    listc.append(c)

1985-09-01 00:00:00
2011-06-01 00:00:00
1986-05-01 00:00:00
2016-05-01 00:00:00
1977-07-01 00:00:00
1990-07-01 00:00:00
2003-07-01 00:00:00
2015-10-01 00:00:00
1995-05-01 00:00:00
1976-02-01 00:00:00
1995-01-01 00:00:00
1978-02-01 00:00:00
2011-05-01 00:00:00
2004-05-01 00:00:00
2010-11-01 00:00:00
2012-09-01 00:00:00
2013-01-01 00:00:00
1990-11-01 00:00:00
1981-07-01 00:00:00
1983-05-01 00:00:00
1995-07-01 00:00:00
1993-04-01 00:00:00
2005-05-01 00:00:00
1998-12-01 00:00:00
2007-01-01 00:00:00
2016-02-01 00:00:00
1979-08-01 00:00:00
2014-10-01 00:00:00
1988-08-01 00:00:00
2015-09-01 00:00:00
1976-04-01 00:00:00
1979-11-01 00:00:00
2000-02-01 00:00:00
1986-10-01 00:00:00
2002-06-01 00:00:00
1981-09-01 00:00:00
2007-06-01 00:00:00
1989-04-01 00:00:00
1999-09-01 00:00:00
1980-10-01 00:00:00
2009-12-01 00:00:00
1992-07-01 00:00:00
2006-05-01 00:00:00
2008-08-01 00:00:00
1993-02-01 00:00:00
2010-02-01 00:00:00
1985-04-01 00:00:00
1984-09-01 00:00:00
1986-04-01 00:00:00
2007-04-01 00:00:00
1974-09-01 00:00:00
2013-09-01 00:00:00
1985-07-01 00:00:00
2004-08-01 00:00:00
2012-05-01 00:00:00
1977-02-01 00:00:00
1987-01-01 00:00:00
1983-09-01 00:00:00
2013-01-01 00:00:00
2010-03-01 00:00:00
2009-08-01 00:00:00
2007-09-01 00:00:00
2011-12-01 00:00:00
2004-01-01 00:00:00
1995-11-01 00:00:00
2008-09-01 00:00:00
1983-02-01 00:00:00
1983-03-01 00:00:00
1979-08-01 00:00:00
2009-01-01 00:00:00
1993-01-01 00:00:00
1974-03-01 00:00:00
1994-01-01 00:00:00
1992-12-01 00:00:00
2004-11-01 00:00:00
1977-01-01 00:00:00
2002-03-01 00:00:00
2000-02-01 00:00:00
2004-05-01 00:00:00
2006-07-01 00:00:00
1994-02-01 00:00:00
1977-04-01 00:00:00
1992-10-01 00:00:00
1995-02-01 00:00:00
1989-02-01 00:00:00
1978-12-01 00:00:00
2007-01-01 00:00:00
1976-06-01 00:00:00
2011-05-01 00:00:00
1975-03-01 00:00:00
1978-01-01 00:00:00
1975-07-01 00:00:00
2012-11-01 00:00:00

In [56]:
print(len(listc))

93

In [57]:
expression5 = r'(?:\d{1,2})(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,\w]* (?:\d{ ,2}, )?\d{4}'

print(df[321])  # need to fix line 321

2June, 1999 Audit C Score Current:

In [58]:
expression5 = r'(?:\d{1,2})(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,\w]* (?:\d{ ,2}, )?\d{4}'
list5 = []

result13 = re.findall(expression5, "2June, 1999")
x = result13[0][0] + ' ' + result13[0][1:] 
list5.append(x)
print(list5)

['2 June, 1999']

In [59]:
listd = []

for item in list5:
    d = str(parse(item, dayfirst=False))
    print(d)
    listd.append(d)

1999-06-02 00:00:00

In [60]:
expression6 = r'(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,]* [.,\s]?\d{4}'

In [61]:
# test case for expression6
line15 = "dCelexa: most helpful, came off half-way through sr yr (Feb 1994) b/c had been doing well enough to not need it"
line16 = ") Paxil (Jan 1978) : sedation"
line17 = "Hep C and HIV negative, LFTs WNL (October 1996)Problems Opioid dependence"
line18 = "sNovember 1997 - suicidal ideation - HHR"

In [62]:
result15 = re.findall(expression6, line15)
result16 = re.findall(expression6, line16)
result17 = re.findall(expression6, line17)
result18 = re.findall(expression6, line18)

In [63]:
print(result15)
print(result16)
print(result17)
print(result18)

['Feb 1994']
['Jan 1978']
['October 1996']
['November 1997']

In [64]:
expression6 = r'(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,]* [.,\s]?\d{4}'

list6 = []

for line in df[322:345]:
    
    result6 = re.findall(expression6, line)
    if result6 != []:
        list6.append(result6[0])
print(list6)

['October 1991', 'March 1973', 'October 1996', 'Jun 2007', 'October 1995', 'April 1999', 'May, 2001', 'March, 2000', 'April 1988', 'December 1993', 'June 1974', 'November 1997', 'July 1986', 'February 1973', 'March 1978', 'Dec 2007', 'Apr, 1998', 'March, 2005', 'May 1980', 'Nov 2007', 'March 1976']

In [65]:
len(df[322:343])

21

In [66]:
len(list6)

21

In [67]:
list66 = []
for item in list6:
    x = "01 " + item
    list66.append(x)

print(list66)

['01 October 1991', '01 March 1973', '01 October 1996', '01 Jun 2007', '01 October 1995', '01 April 1999', '01 May, 2001', '01 March, 2000', '01 April 1988', '01 December 1993', '01 June 1974', '01 November 1997', '01 July 1986', '01 February 1973', '01 March 1978', '01 Dec 2007', '01 Apr, 1998', '01 March, 2005', '01 May 1980', '01 Nov 2007', '01 March 1976']

In [68]:
liste = []

for item in list66:
    e = str(parse(item, dayfirst=False))
    print(e)
    liste.append(e)

1991-10-01 00:00:00
1973-03-01 00:00:00
1996-10-01 00:00:00
2007-06-01 00:00:00
1995-10-01 00:00:00
1999-04-01 00:00:00
2001-05-01 00:00:00
2000-03-01 00:00:00
1988-04-01 00:00:00
1993-12-01 00:00:00
1974-06-01 00:00:00
1997-11-01 00:00:00
1986-07-01 00:00:00
1973-02-01 00:00:00
1978-03-01 00:00:00
2007-12-01 00:00:00
1998-04-01 00:00:00
2005-03-01 00:00:00
1980-05-01 00:00:00
2007-11-01 00:00:00
1976-03-01 00:00:00

In [69]:
expression7 = r'\d{0,2}[/-]\d{2,4}'

In [70]:
# test cases for expression7
line19 = "12/2005 Family Psych History: Family History of Suicidal Behavior: None"
line20 = ".Mother died, 1/1983."
line21 = "see above.   Last cutting in 3/1995 Violent Behavior Hx of Violent Behavior: No"

In [71]:
result19 = re.findall(expression7, line19)
result20 = re.findall(expression7, line20)
result21 = re.findall(expression7, line21)

In [72]:
print(result19)
print(result20)
print(result21)

['12/2005']
['1/1983']
['3/1995']

In [73]:
expression7 = r'\d{,2}[/-]\d{2,4}'

list7 = []

for line in df[343:455]:
    
    result7 = re.findall(expression7, line)
    if result7 != []:
        list7.append(result7[0])
print(list7)

['6/1998', '6/2005', '10/1973', '9/2005', '03/1980', '12/2005', '5/1987', '5/2004', '8/1974', '3/1986', '10/1997', '3/1993', '3/1981', '9/2003', '10/1993', '1/1983', '7/1994', '12/2008', '10/1980', '8/2003', '12/1975', '11/2010', '7/1997', '7/2014', '9/2001', '8/1986', '1/1978', '9/1975', '1/2009', '5/1995', '8/1989', '11/2000', '06/1973', '2/1999', '6/2001', '12/1978', '8/2009', '7/1973', '1/2014', '09/1975', '12/2012', '5/1999', '7/1989', '7/2009', '11/1998', '3/1995', '2/2009', '08/1988', '4/2007', '5/2000', '4/2012', '10/2001', '2/1977', '8/2008', '2/1983', '5/1979', '1/1992', '11/2008', '12/2014', '4/1974', '10/1981', '10/1986', '03/1973', '12/1994', '8/1999', '10/2010', '10/1994', '01/2007', '8/2010', '03/1990', '11/2016', '4/2004', '2/1973', '7/1987', '8/2000', '8/1975', '5/1977', '3/2000', '9/1984', '4/1973', '12/1986', '4/1979', '7/2004', '11/1984', '5/2016', '12/2007', '11/1982', '06/1981', '4/2013', '4/1999', '5/2006', '10/1978', '12/1989', '2/1974', '11/1986', '4/1983', '10/2014', '6/1989', '9/1980', '9/1992', '9/2000', '7/1981', '1/2008', '4/2002', '7/1985', '5/2010', '8/2002', '1/1994', '12/2004', '3/2003', '7/1991', '7/1982']

In [74]:
temp = []
for i in list7:
    x = i.split('/')
    temp.append(x)
temp

[['6', '1998'],
 ['6', '2005'],
 ['10', '1973'],
 ['9', '2005'],
 ['03', '1980'],
 ['12', '2005'],
 ['5', '1987'],
 ['5', '2004'],
 ['8', '1974'],
 ['3', '1986'],
 ['10', '1997'],
 ['3', '1993'],
 ['3', '1981'],
 ['9', '2003'],
 ['10', '1993'],
 ['1', '1983'],
 ['7', '1994'],
 ['12', '2008'],
 ['10', '1980'],
 ['8', '2003'],
 ['12', '1975'],
 ['11', '2010'],
 ['7', '1997'],
 ['7', '2014'],
 ['9', '2001'],
 ['8', '1986'],
 ['1', '1978'],
 ['9', '1975'],
 ['1', '2009'],
 ['5', '1995'],
 ['8', '1989'],
 ['11', '2000'],
 ['06', '1973'],
 ['2', '1999'],
 ['6', '2001'],
 ['12', '1978'],
 ['8', '2009'],
 ['7', '1973'],
 ['1', '2014'],
 ['09', '1975'],
 ['12', '2012'],
 ['5', '1999'],
 ['7', '1989'],
 ['7', '2009'],
 ['11', '1998'],
 ['3', '1995'],
 ['2', '2009'],
 ['08', '1988'],
 ['4', '2007'],
 ['5', '2000'],
 ['4', '2012'],
 ['10', '2001'],
 ['2', '1977'],
 ['8', '2008'],
 ['2', '1983'],
 ['5', '1979'],
 ['1', '1992'],
 ['11', '2008'],
 ['12', '2014'],
 ['4', '1974'],
 ['10', '1981'],
 ['10', '1986'],
 ['03', '1973'],
 ['12', '1994'],
 ['8', '1999'],
 ['10', '2010'],
 ['10', '1994'],
 ['01', '2007'],
 ['8', '2010'],
 ['03', '1990'],
 ['11', '2016'],
 ['4', '2004'],
 ['2', '1973'],
 ['7', '1987'],
 ['8', '2000'],
 ['8', '1975'],
 ['5', '1977'],
 ['3', '2000'],
 ['9', '1984'],
 ['4', '1973'],
 ['12', '1986'],
 ['4', '1979'],
 ['7', '2004'],
 ['11', '1984'],
 ['5', '2016'],
 ['12', '2007'],
 ['11', '1982'],
 ['06', '1981'],
 ['4', '2013'],
 ['4', '1999'],
 ['5', '2006'],
 ['10', '1978'],
 ['12', '1989'],
 ['2', '1974'],
 ['11', '1986'],
 ['4', '1983'],
 ['10', '2014'],
 ['6', '1989'],
 ['9', '1980'],
 ['9', '1992'],
 ['9', '2000'],
 ['7', '1981'],
 ['1', '2008'],
 ['4', '2002'],
 ['7', '1985'],
 ['5', '2010'],
 ['8', '2002'],
 ['1', '1994'],
 ['12', '2004'],
 ['3', '2003'],
 ['7', '1991'],
 ['7', '1982']]

In [75]:
# put in format of month/day/year
list77 = []
for i in temp:
    b = i[0] + "/01/" + i[1]
    list77.append(b)
list77

['6/01/1998',
 '6/01/2005',
 '10/01/1973',
 '9/01/2005',
 '03/01/1980',
 '12/01/2005',
 '5/01/1987',
 '5/01/2004',
 '8/01/1974',
 '3/01/1986',
 '10/01/1997',
 '3/01/1993',
 '3/01/1981',
 '9/01/2003',
 '10/01/1993',
 '1/01/1983',
 '7/01/1994',
 '12/01/2008',
 '10/01/1980',
 '8/01/2003',
 '12/01/1975',
 '11/01/2010',
 '7/01/1997',
 '7/01/2014',
 '9/01/2001',
 '8/01/1986',
 '1/01/1978',
 '9/01/1975',
 '1/01/2009',
 '5/01/1995',
 '8/01/1989',
 '11/01/2000',
 '06/01/1973',
 '2/01/1999',
 '6/01/2001',
 '12/01/1978',
 '8/01/2009',
 '7/01/1973',
 '1/01/2014',
 '09/01/1975',
 '12/01/2012',
 '5/01/1999',
 '7/01/1989',
 '7/01/2009',
 '11/01/1998',
 '3/01/1995',
 '2/01/2009',
 '08/01/1988',
 '4/01/2007',
 '5/01/2000',
 '4/01/2012',
 '10/01/2001',
 '2/01/1977',
 '8/01/2008',
 '2/01/1983',
 '5/01/1979',
 '1/01/1992',
 '11/01/2008',
 '12/01/2014',
 '4/01/1974',
 '10/01/1981',
 '10/01/1986',
 '03/01/1973',
 '12/01/1994',
 '8/01/1999',
 '10/01/2010',
 '10/01/1994',
 '01/01/2007',
 '8/01/2010',
 '03/01/1990',
 '11/01/2016',
 '4/01/2004',
 '2/01/1973',
 '7/01/1987',
 '8/01/2000',
 '8/01/1975',
 '5/01/1977',
 '3/01/2000',
 '9/01/1984',
 '4/01/1973',
 '12/01/1986',
 '4/01/1979',
 '7/01/2004',
 '11/01/1984',
 '5/01/2016',
 '12/01/2007',
 '11/01/1982',
 '06/01/1981',
 '4/01/2013',
 '4/01/1999',
 '5/01/2006',
 '10/01/1978',
 '12/01/1989',
 '2/01/1974',
 '11/01/1986',
 '4/01/1983',
 '10/01/2014',
 '6/01/1989',
 '9/01/1980',
 '9/01/1992',
 '9/01/2000',
 '7/01/1981',
 '1/01/2008',
 '4/01/2002',
 '7/01/1985',
 '5/01/2010',
 '8/01/2002',
 '1/01/1994',
 '12/01/2004',
 '3/01/2003',
 '7/01/1991',
 '7/01/1982']

In [76]:
listf = []

for item in list77:
    f = str(parse(item, dayfirst=False))
    listf.append(f)
    
print(listf)

['1998-06-01 00:00:00', '2005-06-01 00:00:00', '1973-10-01 00:00:00', '2005-09-01 00:00:00', '1980-03-01 00:00:00', '2005-12-01 00:00:00', '1987-05-01 00:00:00', '2004-05-01 00:00:00', '1974-08-01 00:00:00', '1986-03-01 00:00:00', '1997-10-01 00:00:00', '1993-03-01 00:00:00', '1981-03-01 00:00:00', '2003-09-01 00:00:00', '1993-10-01 00:00:00', '1983-01-01 00:00:00', '1994-07-01 00:00:00', '2008-12-01 00:00:00', '1980-10-01 00:00:00', '2003-08-01 00:00:00', '1975-12-01 00:00:00', '2010-11-01 00:00:00', '1997-07-01 00:00:00', '2014-07-01 00:00:00', '2001-09-01 00:00:00', '1986-08-01 00:00:00', '1978-01-01 00:00:00', '1975-09-01 00:00:00', '2009-01-01 00:00:00', '1995-05-01 00:00:00', '1989-08-01 00:00:00', '2000-11-01 00:00:00', '1973-06-01 00:00:00', '1999-02-01 00:00:00', '2001-06-01 00:00:00', '1978-12-01 00:00:00', '2009-08-01 00:00:00', '1973-07-01 00:00:00', '2014-01-01 00:00:00', '1975-09-01 00:00:00', '2012-12-01 00:00:00', '1999-05-01 00:00:00', '1989-07-01 00:00:00', '2009-07-01 00:00:00', '1998-11-01 00:00:00', '1995-03-01 00:00:00', '2009-02-01 00:00:00', '1988-08-01 00:00:00', '2007-04-01 00:00:00', '2000-05-01 00:00:00', '2012-04-01 00:00:00', '2001-10-01 00:00:00', '1977-02-01 00:00:00', '2008-08-01 00:00:00', '1983-02-01 00:00:00', '1979-05-01 00:00:00', '1992-01-01 00:00:00', '2008-11-01 00:00:00', '2014-12-01 00:00:00', '1974-04-01 00:00:00', '1981-10-01 00:00:00', '1986-10-01 00:00:00', '1973-03-01 00:00:00', '1994-12-01 00:00:00', '1999-08-01 00:00:00', '2010-10-01 00:00:00', '1994-10-01 00:00:00', '2007-01-01 00:00:00', '2010-08-01 00:00:00', '1990-03-01 00:00:00', '2016-11-01 00:00:00', '2004-04-01 00:00:00', '1973-02-01 00:00:00', '1987-07-01 00:00:00', '2000-08-01 00:00:00', '1975-08-01 00:00:00', '1977-05-01 00:00:00', '2000-03-01 00:00:00', '1984-09-01 00:00:00', '1973-04-01 00:00:00', '1986-12-01 00:00:00', '1979-04-01 00:00:00', '2004-07-01 00:00:00', '1984-11-01 00:00:00', '2016-05-01 00:00:00', '2007-12-01 00:00:00', '1982-11-01 00:00:00', '1981-06-01 00:00:00', '2013-04-01 00:00:00', '1999-04-01 00:00:00', '2006-05-01 00:00:00', '1978-10-01 00:00:00', '1989-12-01 00:00:00', '1974-02-01 00:00:00', '1986-11-01 00:00:00', '1983-04-01 00:00:00', '2014-10-01 00:00:00', '1989-06-01 00:00:00', '1980-09-01 00:00:00', '1992-09-01 00:00:00', '2000-09-01 00:00:00', '1981-07-01 00:00:00', '2008-01-01 00:00:00', '2002-04-01 00:00:00', '1985-07-01 00:00:00', '2010-05-01 00:00:00', '2002-08-01 00:00:00', '1994-01-01 00:00:00', '2004-12-01 00:00:00', '2003-03-01 00:00:00', '1991-07-01 00:00:00', '1982-07-01 00:00:00']

In [77]:
expression8  = r'\d{4}'

In [78]:
#test cases for expression8
line23 = "2008 partial thyroidectomy"
line24 = "Lab: B12 969 2007"
line25 = "eHistory of small right parietal subgaleal hematoma s/p MVA (1993)"
line26 = ".Age, 19, 1976, playing football, frontal impact. out for two weeks from sports."
line27 = "1 Ex-smoker : quit 2012"

In [79]:
result23 = re.findall(expression8, line23)
result24 = re.findall(expression8, line24)
result25 = re.findall(expression8, line25)
result26 = re.findall(expression8, line26)
result27 = re.findall(expression8, line27)

In [80]:
print(result23)
print(result24)
print(result25)
print(result26)
print(result27)

['2008']
['2007']
['1993']
['1976']
['2012']

In [81]:
expression8  = r'\d{4}'

list8 = []

for line in df[455:]:
    
    result8 = re.findall(expression8, line)
    if result8 != []:
        list8.append(result8[0])
print(list8)

['1984', '2000', '2001', '1982', '1998', '2012', '1991', '1988', '2014', '2016', '1976', '1981', '2011', '1997', '2003', '1983', '1999', '2010', '1975', '1972', '2015', '1989', '1994', '1993', '1996', '2013', '1974', '1990', '1995', '2004', '1987', '1973', '1992', '1977', '1985', '2007', '2009', '1986', '1978', '2002', '1979', '2006', '2008', '2005', '1980']

In [82]:
list88 = []
for item in list8:
    x = "01/01/" + item
    list88.append(x)

print(list88)

['01/01/1984', '01/01/2000', '01/01/2001', '01/01/1982', '01/01/1998', '01/01/2012', '01/01/1991', '01/01/1988', '01/01/2014', '01/01/2016', '01/01/1976', '01/01/1981', '01/01/2011', '01/01/1997', '01/01/2003', '01/01/1983', '01/01/1999', '01/01/2010', '01/01/1975', '01/01/1972', '01/01/2015', '01/01/1989', '01/01/1994', '01/01/1993', '01/01/1996', '01/01/2013', '01/01/1974', '01/01/1990', '01/01/1995', '01/01/2004', '01/01/1987', '01/01/1973', '01/01/1992', '01/01/1977', '01/01/1985', '01/01/2007', '01/01/2009', '01/01/1986', '01/01/1978', '01/01/2002', '01/01/1979', '01/01/2006', '01/01/2008', '01/01/2005', '01/01/1980']

In [83]:
listg = []

for item in list88:
    g = str(parse(item, dayfirst=False))
    listg.append(g)
    
print(listg)

['1984-01-01 00:00:00', '2000-01-01 00:00:00', '2001-01-01 00:00:00', '1982-01-01 00:00:00', '1998-01-01 00:00:00', '2012-01-01 00:00:00', '1991-01-01 00:00:00', '1988-01-01 00:00:00', '2014-01-01 00:00:00', '2016-01-01 00:00:00', '1976-01-01 00:00:00', '1981-01-01 00:00:00', '2011-01-01 00:00:00', '1997-01-01 00:00:00', '2003-01-01 00:00:00', '1983-01-01 00:00:00', '1999-01-01 00:00:00', '2010-01-01 00:00:00', '1975-01-01 00:00:00', '1972-01-01 00:00:00', '2015-01-01 00:00:00', '1989-01-01 00:00:00', '1994-01-01 00:00:00', '1993-01-01 00:00:00', '1996-01-01 00:00:00', '2013-01-01 00:00:00', '1974-01-01 00:00:00', '1990-01-01 00:00:00', '1995-01-01 00:00:00', '2004-01-01 00:00:00', '1987-01-01 00:00:00', '1973-01-01 00:00:00', '1992-01-01 00:00:00', '1977-01-01 00:00:00', '1985-01-01 00:00:00', '2007-01-01 00:00:00', '2009-01-01 00:00:00', '1986-01-01 00:00:00', '1978-01-01 00:00:00', '2002-01-01 00:00:00', '1979-01-01 00:00:00', '2006-01-01 00:00:00', '2008-01-01 00:00:00', '2005-01-01 00:00:00', '1980-01-01 00:00:00']

In [84]:
final_list = lista + listb + listc + listd + liste + listf + listg

In [85]:
len(final_list)

500

In [86]:
final_list

['1993-03-25 00:00:00',
 '1985-06-18 00:00:00',
 '1971-07-08 00:00:00',
 '1975-09-27 00:00:00',
 '1996-02-06 00:00:00',
 '1979-07-06 00:00:00',
 '1978-05-18 00:00:00',
 '1989-10-24 00:00:00',
 '1986-03-07 00:00:00',
 '1971-04-10 00:00:00',
 '1985-05-11 00:00:00',
 '1975-04-09 00:00:00',
 '1998-08-01 00:00:00',
 '1972-01-26 00:00:00',
 '1990-05-24 00:00:00',
 '2011-01-25 00:00:00',
 '1982-04-12 00:00:00',
 '1976-10-13 00:00:00',
 '1998-04-24 00:00:00',
 '1977-05-21 00:00:00',
 '1998-07-21 00:00:00',
 '1979-10-21 00:00:00',
 '1990-03-03 00:00:00',
 '1976-02-11 00:00:00',
 '1984-07-25 00:00:00',
 '1982-04-13 00:00:00',
 '1989-09-22 00:00:00',
 '1976-09-02 00:00:00',
 '1971-09-12 00:00:00',
 '1986-10-24 00:00:00',
 '1985-03-31 00:00:00',
 '1972-07-20 00:00:00',
 '1987-04-12 00:00:00',
 '1991-06-20 00:00:00',
 '2012-05-12 00:00:00',
 '1983-03-15 00:00:00',
 '1973-02-14 00:00:00',
 '1988-05-24 00:00:00',
 '1986-07-27 00:00:00',
 '1981-01-14 00:00:00',
 '1975-07-29 00:00:00',
 '1987-06-24 00:00:00',
 '1994-08-14 00:00:00',
 '2002-04-13 00:00:00',
 '1982-08-16 00:00:00',
 '1998-02-15 00:00:00',
 '1991-07-15 00:00:00',
 '1994-06-12 00:00:00',
 '1984-09-17 00:00:00',
 '1975-02-28 00:00:00',
 '1975-11-22 00:00:00',
 '1991-05-24 00:00:00',
 '1992-06-13 00:00:00',
 '1971-07-11 00:00:00',
 '1986-12-26 00:00:00',
 '1987-10-11 00:00:00',
 '1995-03-14 00:00:00',
 '1973-12-01 00:00:00',
 '2010-12-05 00:00:00',
 '1982-08-20 00:00:00',
 '1995-07-24 00:00:00',
 '1983-08-06 00:00:00',
 '1992-02-22 00:00:00',
 '1987-06-28 00:00:00',
 '1994-07-29 00:00:00',
 '1978-08-11 00:00:00',
 '1991-10-29 00:00:00',
 '1991-07-06 00:00:00',
 '1987-01-21 00:00:00',
 '1985-11-03 00:00:00',
 '1982-07-04 00:00:00',
 '1989-04-13 00:00:00',
 '1977-07-11 00:00:00',
 '1974-04-12 00:00:00',
 '1981-09-19 00:00:00',
 '1979-09-06 00:00:00',
 '1987-12-05 00:00:00',
 '1999-01-05 00:00:00',
 '1980-04-22 00:00:00',
 '1998-10-04 00:00:00',
 '1981-06-29 00:00:00',
 '1978-08-04 00:00:00',
 '1974-07-07 00:00:00',
 '2000-09-14 00:00:00',
 '1971-05-18 00:00:00',
 '1981-08-09 00:00:00',
 '1993-06-05 00:00:00',
 '1997-08-09 00:00:00',
 '1982-12-08 00:00:00',
 '1989-08-26 00:00:00',
 '1995-10-13 00:00:00',
 '1991-04-19 00:00:00',
 '2004-04-08 00:00:00',
 '1976-09-20 00:00:00',
 '1990-12-08 00:00:00',
 '1974-04-11 00:00:00',
 '1986-07-18 00:00:00',
 '1991-03-31 00:00:00',
 '1972-05-13 00:00:00',
 '1983-11-14 00:00:00',
 '1992-08-16 00:00:00',
 '1997-10-05 00:00:00',
 '2002-07-18 00:00:00',
 '1982-09-22 00:00:00',
 '1974-02-24 00:00:00',
 '1978-02-03 00:00:00',
 '2006-02-11 00:00:00',
 '1983-08-22 00:00:00',
 '1974-05-04 00:00:00',
 '2011-07-20 00:00:00',
 '1995-06-17 00:00:00',
 '1972-06-10 00:00:00',
 '1982-10-16 00:00:00',
 '1992-12-15 00:00:00',
 '1997-12-08 00:00:00',
 '1989-04-05 00:00:00',
 '1987-12-04 00:00:00',
 '1977-06-20 00:00:00',
 '2006-04-27 00:00:00',
 '1992-07-17 00:00:00',
 '1998-12-22 00:00:00',
 '1996-10-02 00:00:00',
 '1990-11-05 00:00:00',
 '1977-05-04 00:00:00',
 '1996-02-27 00:00:00',
 '2001-01-24 00:00:00',
 '2004-09-10 00:00:00',
 '1982-05-26 00:00:00',
 '2002-06-28 00:00:00',
 '1972-05-06 00:00:00',
 '1987-10-25 00:00:00',
 '1996-10-14 00:00:00',
 '2007-11-30 00:00:00',
 '1994-06-28 00:00:00',
 '1981-01-14 00:00:00',
 '1985-10-10 00:00:00',
 '1985-02-11 00:00:00',
 '1983-02-10 00:00:00',
 '1992-02-05 00:00:00',
 '2012-10-21 00:00:00',
 '1995-02-14 00:00:00',
 '2016-05-30 00:00:00',
 '1996-01-22 00:00:00',
 '1992-10-14 00:00:00',
 '2003-10-06 00:00:00',
 '1999-10-18 00:00:00',
 '2004-11-11 00:00:00',
 '2001-05-30 00:00:00',
 '1978-02-02 00:00:00',
 '1989-09-09 00:00:00',
 '1980-03-12 00:00:00',
 '1990-06-22 00:00:00',
 '2015-09-28 00:00:00',
 '1972-01-13 00:00:00',
 '1974-03-06 00:00:00',
 '1974-10-10 00:00:00',
 '1974-05-26 00:00:00',
 '1990-02-10 00:00:00',
 '2000-08-23 00:00:00',
 '2001-05-26 00:00:00',
 '2007-10-21 00:00:00',
 '2016-10-19 00:00:00',
 '1974-03-05 00:00:00',
 '1994-01-29 00:00:00',
 '1978-10-21 00:00:00',
 '1975-08-18 00:00:00',
 '1996-11-11 00:00:00',
 '1979-10-01 00:00:00',
 '1986-10-13 00:00:00',
 '1995-10-21 00:00:00',
 '2011-01-24 00:00:00',
 '1972-10-04 00:00:00',
 '1993-08-23 00:00:00',
 '2006-10-18 00:00:00',
 '1988-12-04 00:00:00',
 '1983-10-21 00:00:00',
 '2010-05-26 00:00:00',
 '1990-01-18 00:00:00',
 '1985-06-15 00:00:00',
 '1982-12-10 00:00:00',
 '1988-12-09 00:00:00',
 '1995-08-18 00:00:00',
 '1974-06-13 00:00:00',
 '2008-05-26 00:00:00',
 '2002-11-11 00:00:00',
 '1985-08-17 00:00:00',
 '2016-10-13 00:00:00',
 '2008-01-14 00:00:00',
 '2004-03-12 00:00:00',
 '1977-10-21 00:00:00',
 '2000-08-10 00:00:00',
 '1972-11-30 00:00:00',
 '1993-05-06 00:00:00',
 '1995-01-18 00:00:00',
 '1990-04-11 00:00:00',
 '2001-05-30 00:00:00',
 '1994-02-18 00:00:00',
 '1981-02-18 00:00:00',
 '2013-10-11 00:00:00',
 '1986-01-24 00:00:00',
 '1978-07-26 00:00:00',
 '1999-12-23 00:00:00',
 '1989-05-15 00:00:00',
 '1995-09-06 00:00:00',
 '1976-03-10 00:00:00',
 '1983-01-27 00:00:00',
 '1990-10-23 00:00:00',
 '2004-08-12 00:00:00',
 '2012-09-01 00:00:00',
 '1983-07-25 00:00:00',
 '1989-08-11 00:00:00',
 '1992-04-17 00:00:00',
 '1999-07-24 00:00:00',
 '1997-07-11 00:00:00',
 '1974-09-10 00:00:00',
 '1981-08-14 00:00:00',
 '1988-11-11 00:00:00',
 '2011-06-13 00:00:00',
 '1989-05-14 00:00:00',
 '1975-12-14 00:00:00',
 '2012-06-25 00:00:00',
 '1980-10-18 00:00:00',
 '1998-05-15 00:00:00',
 '1974-10-14 00:00:00',
 '1998-07-25 00:00:00',
 '1972-06-15 00:00:00',
 '1991-01-07 00:00:00',
 '2011-09-15 00:00:00',
 '1985-09-01 00:00:00',
 '2011-06-01 00:00:00',
 '1986-05-01 00:00:00',
 '2016-05-01 00:00:00',
 '1977-07-01 00:00:00',
 '1990-07-01 00:00:00',
 '2003-07-01 00:00:00',
 '2015-10-01 00:00:00',
 '1995-05-01 00:00:00',
 '1976-02-01 00:00:00',
 '1995-01-01 00:00:00',
 '1978-02-01 00:00:00',
 '2011-05-01 00:00:00',
 '2004-05-01 00:00:00',
 '2010-11-01 00:00:00',
 '2012-09-01 00:00:00',
 '2013-01-01 00:00:00',
 '1990-11-01 00:00:00',
 '1981-07-01 00:00:00',
 '1983-05-01 00:00:00',
 '1995-07-01 00:00:00',
 '1993-04-01 00:00:00',
 '2005-05-01 00:00:00',
 '1998-12-01 00:00:00',
 '2007-01-01 00:00:00',
 '2016-02-01 00:00:00',
 '1979-08-01 00:00:00',
 '2014-10-01 00:00:00',
 '1988-08-01 00:00:00',
 '2015-09-01 00:00:00',
 '1976-04-01 00:00:00',
 '1979-11-01 00:00:00',
 '2000-02-01 00:00:00',
 '1986-10-01 00:00:00',
 '2002-06-01 00:00:00',
 '1981-09-01 00:00:00',
 '2007-06-01 00:00:00',
 '1989-04-01 00:00:00',
 '1999-09-01 00:00:00',
 '1980-10-01 00:00:00',
 '2009-12-01 00:00:00',
 '1992-07-01 00:00:00',
 '2006-05-01 00:00:00',
 '2008-08-01 00:00:00',
 '1993-02-01 00:00:00',
 '2010-02-01 00:00:00',
 '1985-04-01 00:00:00',
 '1984-09-01 00:00:00',
 '1986-04-01 00:00:00',
 '2007-04-01 00:00:00',
 '1974-09-01 00:00:00',
 '2013-09-01 00:00:00',
 '1985-07-01 00:00:00',
 '2004-08-01 00:00:00',
 '2012-05-01 00:00:00',
 '1977-02-01 00:00:00',
 '1987-01-01 00:00:00',
 '1983-09-01 00:00:00',
 '2013-01-01 00:00:00',
 '2010-03-01 00:00:00',
 '2009-08-01 00:00:00',
 '2007-09-01 00:00:00',
 '2011-12-01 00:00:00',
 '2004-01-01 00:00:00',
 '1995-11-01 00:00:00',
 '2008-09-01 00:00:00',
 '1983-02-01 00:00:00',
 '1983-03-01 00:00:00',
 '1979-08-01 00:00:00',
 '2009-01-01 00:00:00',
 '1993-01-01 00:00:00',
 '1974-03-01 00:00:00',
 '1994-01-01 00:00:00',
 '1992-12-01 00:00:00',
 '2004-11-01 00:00:00',
 '1977-01-01 00:00:00',
 '2002-03-01 00:00:00',
 '2000-02-01 00:00:00',
 '2004-05-01 00:00:00',
 '2006-07-01 00:00:00',
 '1994-02-01 00:00:00',
 '1977-04-01 00:00:00',
 '1992-10-01 00:00:00',
 '1995-02-01 00:00:00',
 '1989-02-01 00:00:00',
 '1978-12-01 00:00:00',
 '2007-01-01 00:00:00',
 '1976-06-01 00:00:00',
 '2011-05-01 00:00:00',
 '1975-03-01 00:00:00',
 '1978-01-01 00:00:00',
 '1975-07-01 00:00:00',
 '2012-11-01 00:00:00',
 '1999-06-02 00:00:00',
 '1991-10-01 00:00:00',
 '1973-03-01 00:00:00',
 '1996-10-01 00:00:00',
 '2007-06-01 00:00:00',
 '1995-10-01 00:00:00',
 '1999-04-01 00:00:00',
 '2001-05-01 00:00:00',
 '2000-03-01 00:00:00',
 '1988-04-01 00:00:00',
 '1993-12-01 00:00:00',
 '1974-06-01 00:00:00',
 '1997-11-01 00:00:00',
 '1986-07-01 00:00:00',
 '1973-02-01 00:00:00',
 '1978-03-01 00:00:00',
 '2007-12-01 00:00:00',
 '1998-04-01 00:00:00',
 '2005-03-01 00:00:00',
 '1980-05-01 00:00:00',
 '2007-11-01 00:00:00',
 '1976-03-01 00:00:00',
 '1998-06-01 00:00:00',
 '2005-06-01 00:00:00',
 '1973-10-01 00:00:00',
 '2005-09-01 00:00:00',
 '1980-03-01 00:00:00',
 '2005-12-01 00:00:00',
 '1987-05-01 00:00:00',
 '2004-05-01 00:00:00',
 '1974-08-01 00:00:00',
 '1986-03-01 00:00:00',
 '1997-10-01 00:00:00',
 '1993-03-01 00:00:00',
 '1981-03-01 00:00:00',
 '2003-09-01 00:00:00',
 '1993-10-01 00:00:00',
 '1983-01-01 00:00:00',
 '1994-07-01 00:00:00',
 '2008-12-01 00:00:00',
 '1980-10-01 00:00:00',
 '2003-08-01 00:00:00',
 '1975-12-01 00:00:00',
 '2010-11-01 00:00:00',
 '1997-07-01 00:00:00',
 '2014-07-01 00:00:00',
 '2001-09-01 00:00:00',
 '1986-08-01 00:00:00',
 '1978-01-01 00:00:00',
 '1975-09-01 00:00:00',
 '2009-01-01 00:00:00',
 '1995-05-01 00:00:00',
 '1989-08-01 00:00:00',
 '2000-11-01 00:00:00',
 '1973-06-01 00:00:00',
 '1999-02-01 00:00:00',
 '2001-06-01 00:00:00',
 '1978-12-01 00:00:00',
 '2009-08-01 00:00:00',
 '1973-07-01 00:00:00',
 '2014-01-01 00:00:00',
 '1975-09-01 00:00:00',
 '2012-12-01 00:00:00',
 '1999-05-01 00:00:00',
 '1989-07-01 00:00:00',
 '2009-07-01 00:00:00',
 '1998-11-01 00:00:00',
 '1995-03-01 00:00:00',
 '2009-02-01 00:00:00',
 '1988-08-01 00:00:00',
 '2007-04-01 00:00:00',
 '2000-05-01 00:00:00',
 '2012-04-01 00:00:00',
 '2001-10-01 00:00:00',
 '1977-02-01 00:00:00',
 '2008-08-01 00:00:00',
 '1983-02-01 00:00:00',
 '1979-05-01 00:00:00',
 '1992-01-01 00:00:00',
 '2008-11-01 00:00:00',
 '2014-12-01 00:00:00',
 '1974-04-01 00:00:00',
 '1981-10-01 00:00:00',
 '1986-10-01 00:00:00',
 '1973-03-01 00:00:00',
 '1994-12-01 00:00:00',
 '1999-08-01 00:00:00',
 '2010-10-01 00:00:00',
 '1994-10-01 00:00:00',
 '2007-01-01 00:00:00',
 '2010-08-01 00:00:00',
 '1990-03-01 00:00:00',
 '2016-11-01 00:00:00',
 '2004-04-01 00:00:00',
 '1973-02-01 00:00:00',
 '1987-07-01 00:00:00',
 '2000-08-01 00:00:00',
 '1975-08-01 00:00:00',
 '1977-05-01 00:00:00',
 '2000-03-01 00:00:00',
 '1984-09-01 00:00:00',
 '1973-04-01 00:00:00',
 '1986-12-01 00:00:00',
 '1979-04-01 00:00:00',
 '2004-07-01 00:00:00',
 '1984-11-01 00:00:00',
 '2016-05-01 00:00:00',
 '2007-12-01 00:00:00',
 '1982-11-01 00:00:00',
 '1981-06-01 00:00:00',
 '2013-04-01 00:00:00',
 '1999-04-01 00:00:00',
 '2006-05-01 00:00:00',
 '1978-10-01 00:00:00',
 '1989-12-01 00:00:00',
 '1974-02-01 00:00:00',
 '1986-11-01 00:00:00',
 '1983-04-01 00:00:00',
 '2014-10-01 00:00:00',
 '1989-06-01 00:00:00',
 '1980-09-01 00:00:00',
 '1992-09-01 00:00:00',
 '2000-09-01 00:00:00',
 '1981-07-01 00:00:00',
 '2008-01-01 00:00:00',
 '2002-04-01 00:00:00',
 '1985-07-01 00:00:00',
 '2010-05-01 00:00:00',
 '2002-08-01 00:00:00',
 '1994-01-01 00:00:00',
 '2004-12-01 00:00:00',
 '2003-03-01 00:00:00',
 '1991-07-01 00:00:00',
 '1982-07-01 00:00:00',
 '1984-01-01 00:00:00',
 '2000-01-01 00:00:00',
 '2001-01-01 00:00:00',
 '1982-01-01 00:00:00',
 '1998-01-01 00:00:00',
 '2012-01-01 00:00:00',
 '1991-01-01 00:00:00',
 '1988-01-01 00:00:00',
 '2014-01-01 00:00:00',
 '2016-01-01 00:00:00',
 '1976-01-01 00:00:00',
 '1981-01-01 00:00:00',
 '2011-01-01 00:00:00',
 '1997-01-01 00:00:00',
 '2003-01-01 00:00:00',
 '1983-01-01 00:00:00',
 '1999-01-01 00:00:00',
 '2010-01-01 00:00:00',
 '1975-01-01 00:00:00',
 '1972-01-01 00:00:00',
 '2015-01-01 00:00:00',
 '1989-01-01 00:00:00',
 '1994-01-01 00:00:00',
 '1993-01-01 00:00:00',
 '1996-01-01 00:00:00',
 '2013-01-01 00:00:00',
 '1974-01-01 00:00:00',
 '1990-01-01 00:00:00',
 '1995-01-01 00:00:00',
 '2004-01-01 00:00:00',
 '1987-01-01 00:00:00',
 '1973-01-01 00:00:00',
 '1992-01-01 00:00:00',
 '1977-01-01 00:00:00',
 '1985-01-01 00:00:00',
 '2007-01-01 00:00:00',
 '2009-01-01 00:00:00',
 '1986-01-01 00:00:00',
 '1978-01-01 00:00:00',
 '2002-01-01 00:00:00',
 '1979-01-01 00:00:00',
 '2006-01-01 00:00:00',
 '2008-01-01 00:00:00',
 '2005-01-01 00:00:00',
 '1980-01-01 00:00:00']

In [87]:
second_list = []

for date in final_list:
    x = date.replace('00:00:00',"")
    second_list.append(x)
    
second_list

['1993-03-25 ',
 '1985-06-18 ',
 '1971-07-08 ',
 '1975-09-27 ',
 '1996-02-06 ',
 '1979-07-06 ',
 '1978-05-18 ',
 '1989-10-24 ',
 '1986-03-07 ',
 '1971-04-10 ',
 '1985-05-11 ',
 '1975-04-09 ',
 '1998-08-01 ',
 '1972-01-26 ',
 '1990-05-24 ',
 '2011-01-25 ',
 '1982-04-12 ',
 '1976-10-13 ',
 '1998-04-24 ',
 '1977-05-21 ',
 '1998-07-21 ',
 '1979-10-21 ',
 '1990-03-03 ',
 '1976-02-11 ',
 '1984-07-25 ',
 '1982-04-13 ',
 '1989-09-22 ',
 '1976-09-02 ',
 '1971-09-12 ',
 '1986-10-24 ',
 '1985-03-31 ',
 '1972-07-20 ',
 '1987-04-12 ',
 '1991-06-20 ',
 '2012-05-12 ',
 '1983-03-15 ',
 '1973-02-14 ',
 '1988-05-24 ',
 '1986-07-27 ',
 '1981-01-14 ',
 '1975-07-29 ',
 '1987-06-24 ',
 '1994-08-14 ',
 '2002-04-13 ',
 '1982-08-16 ',
 '1998-02-15 ',
 '1991-07-15 ',
 '1994-06-12 ',
 '1984-09-17 ',
 '1975-02-28 ',
 '1975-11-22 ',
 '1991-05-24 ',
 '1992-06-13 ',
 '1971-07-11 ',
 '1986-12-26 ',
 '1987-10-11 ',
 '1995-03-14 ',
 '1973-12-01 ',
 '2010-12-05 ',
 '1982-08-20 ',
 '1995-07-24 ',
 '1983-08-06 ',
 '1992-02-22 ',
 '1987-06-28 ',
 '1994-07-29 ',
 '1978-08-11 ',
 '1991-10-29 ',
 '1991-07-06 ',
 '1987-01-21 ',
 '1985-11-03 ',
 '1982-07-04 ',
 '1989-04-13 ',
 '1977-07-11 ',
 '1974-04-12 ',
 '1981-09-19 ',
 '1979-09-06 ',
 '1987-12-05 ',
 '1999-01-05 ',
 '1980-04-22 ',
 '1998-10-04 ',
 '1981-06-29 ',
 '1978-08-04 ',
 '1974-07-07 ',
 '2000-09-14 ',
 '1971-05-18 ',
 '1981-08-09 ',
 '1993-06-05 ',
 '1997-08-09 ',
 '1982-12-08 ',
 '1989-08-26 ',
 '1995-10-13 ',
 '1991-04-19 ',
 '2004-04-08 ',
 '1976-09-20 ',
 '1990-12-08 ',
 '1974-04-11 ',
 '1986-07-18 ',
 '1991-03-31 ',
 '1972-05-13 ',
 '1983-11-14 ',
 '1992-08-16 ',
 '1997-10-05 ',
 '2002-07-18 ',
 '1982-09-22 ',
 '1974-02-24 ',
 '1978-02-03 ',
 '2006-02-11 ',
 '1983-08-22 ',
 '1974-05-04 ',
 '2011-07-20 ',
 '1995-06-17 ',
 '1972-06-10 ',
 '1982-10-16 ',
 '1992-12-15 ',
 '1997-12-08 ',
 '1989-04-05 ',
 '1987-12-04 ',
 '1977-06-20 ',
 '2006-04-27 ',
 '1992-07-17 ',
 '1998-12-22 ',
 '1996-10-02 ',
 '1990-11-05 ',
 '1977-05-04 ',
 '1996-02-27 ',
 '2001-01-24 ',
 '2004-09-10 ',
 '1982-05-26 ',
 '2002-06-28 ',
 '1972-05-06 ',
 '1987-10-25 ',
 '1996-10-14 ',
 '2007-11-30 ',
 '1994-06-28 ',
 '1981-01-14 ',
 '1985-10-10 ',
 '1985-02-11 ',
 '1983-02-10 ',
 '1992-02-05 ',
 '2012-10-21 ',
 '1995-02-14 ',
 '2016-05-30 ',
 '1996-01-22 ',
 '1992-10-14 ',
 '2003-10-06 ',
 '1999-10-18 ',
 '2004-11-11 ',
 '2001-05-30 ',
 '1978-02-02 ',
 '1989-09-09 ',
 '1980-03-12 ',
 '1990-06-22 ',
 '2015-09-28 ',
 '1972-01-13 ',
 '1974-03-06 ',
 '1974-10-10 ',
 '1974-05-26 ',
 '1990-02-10 ',
 '2000-08-23 ',
 '2001-05-26 ',
 '2007-10-21 ',
 '2016-10-19 ',
 '1974-03-05 ',
 '1994-01-29 ',
 '1978-10-21 ',
 '1975-08-18 ',
 '1996-11-11 ',
 '1979-10-01 ',
 '1986-10-13 ',
 '1995-10-21 ',
 '2011-01-24 ',
 '1972-10-04 ',
 '1993-08-23 ',
 '2006-10-18 ',
 '1988-12-04 ',
 '1983-10-21 ',
 '2010-05-26 ',
 '1990-01-18 ',
 '1985-06-15 ',
 '1982-12-10 ',
 '1988-12-09 ',
 '1995-08-18 ',
 '1974-06-13 ',
 '2008-05-26 ',
 '2002-11-11 ',
 '1985-08-17 ',
 '2016-10-13 ',
 '2008-01-14 ',
 '2004-03-12 ',
 '1977-10-21 ',
 '2000-08-10 ',
 '1972-11-30 ',
 '1993-05-06 ',
 '1995-01-18 ',
 '1990-04-11 ',
 '2001-05-30 ',
 '1994-02-18 ',
 '1981-02-18 ',
 '2013-10-11 ',
 '1986-01-24 ',
 '1978-07-26 ',
 '1999-12-23 ',
 '1989-05-15 ',
 '1995-09-06 ',
 '1976-03-10 ',
 '1983-01-27 ',
 '1990-10-23 ',
 '2004-08-12 ',
 '2012-09-01 ',
 '1983-07-25 ',
 '1989-08-11 ',
 '1992-04-17 ',
 '1999-07-24 ',
 '1997-07-11 ',
 '1974-09-10 ',
 '1981-08-14 ',
 '1988-11-11 ',
 '2011-06-13 ',
 '1989-05-14 ',
 '1975-12-14 ',
 '2012-06-25 ',
 '1980-10-18 ',
 '1998-05-15 ',
 '1974-10-14 ',
 '1998-07-25 ',
 '1972-06-15 ',
 '1991-01-07 ',
 '2011-09-15 ',
 '1985-09-01 ',
 '2011-06-01 ',
 '1986-05-01 ',
 '2016-05-01 ',
 '1977-07-01 ',
 '1990-07-01 ',
 '2003-07-01 ',
 '2015-10-01 ',
 '1995-05-01 ',
 '1976-02-01 ',
 '1995-01-01 ',
 '1978-02-01 ',
 '2011-05-01 ',
 '2004-05-01 ',
 '2010-11-01 ',
 '2012-09-01 ',
 '2013-01-01 ',
 '1990-11-01 ',
 '1981-07-01 ',
 '1983-05-01 ',
 '1995-07-01 ',
 '1993-04-01 ',
 '2005-05-01 ',
 '1998-12-01 ',
 '2007-01-01 ',
 '2016-02-01 ',
 '1979-08-01 ',
 '2014-10-01 ',
 '1988-08-01 ',
 '2015-09-01 ',
 '1976-04-01 ',
 '1979-11-01 ',
 '2000-02-01 ',
 '1986-10-01 ',
 '2002-06-01 ',
 '1981-09-01 ',
 '2007-06-01 ',
 '1989-04-01 ',
 '1999-09-01 ',
 '1980-10-01 ',
 '2009-12-01 ',
 '1992-07-01 ',
 '2006-05-01 ',
 '2008-08-01 ',
 '1993-02-01 ',
 '2010-02-01 ',
 '1985-04-01 ',
 '1984-09-01 ',
 '1986-04-01 ',
 '2007-04-01 ',
 '1974-09-01 ',
 '2013-09-01 ',
 '1985-07-01 ',
 '2004-08-01 ',
 '2012-05-01 ',
 '1977-02-01 ',
 '1987-01-01 ',
 '1983-09-01 ',
 '2013-01-01 ',
 '2010-03-01 ',
 '2009-08-01 ',
 '2007-09-01 ',
 '2011-12-01 ',
 '2004-01-01 ',
 '1995-11-01 ',
 '2008-09-01 ',
 '1983-02-01 ',
 '1983-03-01 ',
 '1979-08-01 ',
 '2009-01-01 ',
 '1993-01-01 ',
 '1974-03-01 ',
 '1994-01-01 ',
 '1992-12-01 ',
 '2004-11-01 ',
 '1977-01-01 ',
 '2002-03-01 ',
 '2000-02-01 ',
 '2004-05-01 ',
 '2006-07-01 ',
 '1994-02-01 ',
 '1977-04-01 ',
 '1992-10-01 ',
 '1995-02-01 ',
 '1989-02-01 ',
 '1978-12-01 ',
 '2007-01-01 ',
 '1976-06-01 ',
 '2011-05-01 ',
 '1975-03-01 ',
 '1978-01-01 ',
 '1975-07-01 ',
 '2012-11-01 ',
 '1999-06-02 ',
 '1991-10-01 ',
 '1973-03-01 ',
 '1996-10-01 ',
 '2007-06-01 ',
 '1995-10-01 ',
 '1999-04-01 ',
 '2001-05-01 ',
 '2000-03-01 ',
 '1988-04-01 ',
 '1993-12-01 ',
 '1974-06-01 ',
 '1997-11-01 ',
 '1986-07-01 ',
 '1973-02-01 ',
 '1978-03-01 ',
 '2007-12-01 ',
 '1998-04-01 ',
 '2005-03-01 ',
 '1980-05-01 ',
 '2007-11-01 ',
 '1976-03-01 ',
 '1998-06-01 ',
 '2005-06-01 ',
 '1973-10-01 ',
 '2005-09-01 ',
 '1980-03-01 ',
 '2005-12-01 ',
 '1987-05-01 ',
 '2004-05-01 ',
 '1974-08-01 ',
 '1986-03-01 ',
 '1997-10-01 ',
 '1993-03-01 ',
 '1981-03-01 ',
 '2003-09-01 ',
 '1993-10-01 ',
 '1983-01-01 ',
 '1994-07-01 ',
 '2008-12-01 ',
 '1980-10-01 ',
 '2003-08-01 ',
 '1975-12-01 ',
 '2010-11-01 ',
 '1997-07-01 ',
 '2014-07-01 ',
 '2001-09-01 ',
 '1986-08-01 ',
 '1978-01-01 ',
 '1975-09-01 ',
 '2009-01-01 ',
 '1995-05-01 ',
 '1989-08-01 ',
 '2000-11-01 ',
 '1973-06-01 ',
 '1999-02-01 ',
 '2001-06-01 ',
 '1978-12-01 ',
 '2009-08-01 ',
 '1973-07-01 ',
 '2014-01-01 ',
 '1975-09-01 ',
 '2012-12-01 ',
 '1999-05-01 ',
 '1989-07-01 ',
 '2009-07-01 ',
 '1998-11-01 ',
 '1995-03-01 ',
 '2009-02-01 ',
 '1988-08-01 ',
 '2007-04-01 ',
 '2000-05-01 ',
 '2012-04-01 ',
 '2001-10-01 ',
 '1977-02-01 ',
 '2008-08-01 ',
 '1983-02-01 ',
 '1979-05-01 ',
 '1992-01-01 ',
 '2008-11-01 ',
 '2014-12-01 ',
 '1974-04-01 ',
 '1981-10-01 ',
 '1986-10-01 ',
 '1973-03-01 ',
 '1994-12-01 ',
 '1999-08-01 ',
 '2010-10-01 ',
 '1994-10-01 ',
 '2007-01-01 ',
 '2010-08-01 ',
 '1990-03-01 ',
 '2016-11-01 ',
 '2004-04-01 ',
 '1973-02-01 ',
 '1987-07-01 ',
 '2000-08-01 ',
 '1975-08-01 ',
 '1977-05-01 ',
 '2000-03-01 ',
 '1984-09-01 ',
 '1973-04-01 ',
 '1986-12-01 ',
 '1979-04-01 ',
 '2004-07-01 ',
 '1984-11-01 ',
 '2016-05-01 ',
 '2007-12-01 ',
 '1982-11-01 ',
 '1981-06-01 ',
 '2013-04-01 ',
 '1999-04-01 ',
 '2006-05-01 ',
 '1978-10-01 ',
 '1989-12-01 ',
 '1974-02-01 ',
 '1986-11-01 ',
 '1983-04-01 ',
 '2014-10-01 ',
 '1989-06-01 ',
 '1980-09-01 ',
 '1992-09-01 ',
 '2000-09-01 ',
 '1981-07-01 ',
 '2008-01-01 ',
 '2002-04-01 ',
 '1985-07-01 ',
 '2010-05-01 ',
 '2002-08-01 ',
 '1994-01-01 ',
 '2004-12-01 ',
 '2003-03-01 ',
 '1991-07-01 ',
 '1982-07-01 ',
 '1984-01-01 ',
 '2000-01-01 ',
 '2001-01-01 ',
 '1982-01-01 ',
 '1998-01-01 ',
 '2012-01-01 ',
 '1991-01-01 ',
 '1988-01-01 ',
 '2014-01-01 ',
 '2016-01-01 ',
 '1976-01-01 ',
 '1981-01-01 ',
 '2011-01-01 ',
 '1997-01-01 ',
 '2003-01-01 ',
 '1983-01-01 ',
 '1999-01-01 ',
 '2010-01-01 ',
 '1975-01-01 ',
 '1972-01-01 ',
 '2015-01-01 ',
 '1989-01-01 ',
 '1994-01-01 ',
 '1993-01-01 ',
 '1996-01-01 ',
 '2013-01-01 ',
 '1974-01-01 ',
 '1990-01-01 ',
 '1995-01-01 ',
 '2004-01-01 ',
 '1987-01-01 ',
 '1973-01-01 ',
 '1992-01-01 ',
 '1977-01-01 ',
 '1985-01-01 ',
 '2007-01-01 ',
 '2009-01-01 ',
 '1986-01-01 ',
 '1978-01-01 ',
 '2002-01-01 ',
 '1979-01-01 ',
 '2006-01-01 ',
 '2008-01-01 ',
 '2005-01-01 ',
 '1980-01-01 ']

In [88]:
splitlist =[]
for date in second_list:
    b = date.replace('-', ' ')
    splitlist.append(b)
splitlist

['1993 03 25 ',
 '1985 06 18 ',
 '1971 07 08 ',
 '1975 09 27 ',
 '1996 02 06 ',
 '1979 07 06 ',
 '1978 05 18 ',
 '1989 10 24 ',
 '1986 03 07 ',
 '1971 04 10 ',
 '1985 05 11 ',
 '1975 04 09 ',
 '1998 08 01 ',
 '1972 01 26 ',
 '1990 05 24 ',
 '2011 01 25 ',
 '1982 04 12 ',
 '1976 10 13 ',
 '1998 04 24 ',
 '1977 05 21 ',
 '1998 07 21 ',
 '1979 10 21 ',
 '1990 03 03 ',
 '1976 02 11 ',
 '1984 07 25 ',
 '1982 04 13 ',
 '1989 09 22 ',
 '1976 09 02 ',
 '1971 09 12 ',
 '1986 10 24 ',
 '1985 03 31 ',
 '1972 07 20 ',
 '1987 04 12 ',
 '1991 06 20 ',
 '2012 05 12 ',
 '1983 03 15 ',
 '1973 02 14 ',
 '1988 05 24 ',
 '1986 07 27 ',
 '1981 01 14 ',
 '1975 07 29 ',
 '1987 06 24 ',
 '1994 08 14 ',
 '2002 04 13 ',
 '1982 08 16 ',
 '1998 02 15 ',
 '1991 07 15 ',
 '1994 06 12 ',
 '1984 09 17 ',
 '1975 02 28 ',
 '1975 11 22 ',
 '1991 05 24 ',
 '1992 06 13 ',
 '1971 07 11 ',
 '1986 12 26 ',
 '1987 10 11 ',
 '1995 03 14 ',
 '1973 12 01 ',
 '2010 12 05 ',
 '1982 08 20 ',
 '1995 07 24 ',
 '1983 08 06 ',
 '1992 02 22 ',
 '1987 06 28 ',
 '1994 07 29 ',
 '1978 08 11 ',
 '1991 10 29 ',
 '1991 07 06 ',
 '1987 01 21 ',
 '1985 11 03 ',
 '1982 07 04 ',
 '1989 04 13 ',
 '1977 07 11 ',
 '1974 04 12 ',
 '1981 09 19 ',
 '1979 09 06 ',
 '1987 12 05 ',
 '1999 01 05 ',
 '1980 04 22 ',
 '1998 10 04 ',
 '1981 06 29 ',
 '1978 08 04 ',
 '1974 07 07 ',
 '2000 09 14 ',
 '1971 05 18 ',
 '1981 08 09 ',
 '1993 06 05 ',
 '1997 08 09 ',
 '1982 12 08 ',
 '1989 08 26 ',
 '1995 10 13 ',
 '1991 04 19 ',
 '2004 04 08 ',
 '1976 09 20 ',
 '1990 12 08 ',
 '1974 04 11 ',
 '1986 07 18 ',
 '1991 03 31 ',
 '1972 05 13 ',
 '1983 11 14 ',
 '1992 08 16 ',
 '1997 10 05 ',
 '2002 07 18 ',
 '1982 09 22 ',
 '1974 02 24 ',
 '1978 02 03 ',
 '2006 02 11 ',
 '1983 08 22 ',
 '1974 05 04 ',
 '2011 07 20 ',
 '1995 06 17 ',
 '1972 06 10 ',
 '1982 10 16 ',
 '1992 12 15 ',
 '1997 12 08 ',
 '1989 04 05 ',
 '1987 12 04 ',
 '1977 06 20 ',
 '2006 04 27 ',
 '1992 07 17 ',
 '1998 12 22 ',
 '1996 10 02 ',
 '1990 11 05 ',
 '1977 05 04 ',
 '1996 02 27 ',
 '2001 01 24 ',
 '2004 09 10 ',
 '1982 05 26 ',
 '2002 06 28 ',
 '1972 05 06 ',
 '1987 10 25 ',
 '1996 10 14 ',
 '2007 11 30 ',
 '1994 06 28 ',
 '1981 01 14 ',
 '1985 10 10 ',
 '1985 02 11 ',
 '1983 02 10 ',
 '1992 02 05 ',
 '2012 10 21 ',
 '1995 02 14 ',
 '2016 05 30 ',
 '1996 01 22 ',
 '1992 10 14 ',
 '2003 10 06 ',
 '1999 10 18 ',
 '2004 11 11 ',
 '2001 05 30 ',
 '1978 02 02 ',
 '1989 09 09 ',
 '1980 03 12 ',
 '1990 06 22 ',
 '2015 09 28 ',
 '1972 01 13 ',
 '1974 03 06 ',
 '1974 10 10 ',
 '1974 05 26 ',
 '1990 02 10 ',
 '2000 08 23 ',
 '2001 05 26 ',
 '2007 10 21 ',
 '2016 10 19 ',
 '1974 03 05 ',
 '1994 01 29 ',
 '1978 10 21 ',
 '1975 08 18 ',
 '1996 11 11 ',
 '1979 10 01 ',
 '1986 10 13 ',
 '1995 10 21 ',
 '2011 01 24 ',
 '1972 10 04 ',
 '1993 08 23 ',
 '2006 10 18 ',
 '1988 12 04 ',
 '1983 10 21 ',
 '2010 05 26 ',
 '1990 01 18 ',
 '1985 06 15 ',
 '1982 12 10 ',
 '1988 12 09 ',
 '1995 08 18 ',
 '1974 06 13 ',
 '2008 05 26 ',
 '2002 11 11 ',
 '1985 08 17 ',
 '2016 10 13 ',
 '2008 01 14 ',
 '2004 03 12 ',
 '1977 10 21 ',
 '2000 08 10 ',
 '1972 11 30 ',
 '1993 05 06 ',
 '1995 01 18 ',
 '1990 04 11 ',
 '2001 05 30 ',
 '1994 02 18 ',
 '1981 02 18 ',
 '2013 10 11 ',
 '1986 01 24 ',
 '1978 07 26 ',
 '1999 12 23 ',
 '1989 05 15 ',
 '1995 09 06 ',
 '1976 03 10 ',
 '1983 01 27 ',
 '1990 10 23 ',
 '2004 08 12 ',
 '2012 09 01 ',
 '1983 07 25 ',
 '1989 08 11 ',
 '1992 04 17 ',
 '1999 07 24 ',
 '1997 07 11 ',
 '1974 09 10 ',
 '1981 08 14 ',
 '1988 11 11 ',
 '2011 06 13 ',
 '1989 05 14 ',
 '1975 12 14 ',
 '2012 06 25 ',
 '1980 10 18 ',
 '1998 05 15 ',
 '1974 10 14 ',
 '1998 07 25 ',
 '1972 06 15 ',
 '1991 01 07 ',
 '2011 09 15 ',
 '1985 09 01 ',
 '2011 06 01 ',
 '1986 05 01 ',
 '2016 05 01 ',
 '1977 07 01 ',
 '1990 07 01 ',
 '2003 07 01 ',
 '2015 10 01 ',
 '1995 05 01 ',
 '1976 02 01 ',
 '1995 01 01 ',
 '1978 02 01 ',
 '2011 05 01 ',
 '2004 05 01 ',
 '2010 11 01 ',
 '2012 09 01 ',
 '2013 01 01 ',
 '1990 11 01 ',
 '1981 07 01 ',
 '1983 05 01 ',
 '1995 07 01 ',
 '1993 04 01 ',
 '2005 05 01 ',
 '1998 12 01 ',
 '2007 01 01 ',
 '2016 02 01 ',
 '1979 08 01 ',
 '2014 10 01 ',
 '1988 08 01 ',
 '2015 09 01 ',
 '1976 04 01 ',
 '1979 11 01 ',
 '2000 02 01 ',
 '1986 10 01 ',
 '2002 06 01 ',
 '1981 09 01 ',
 '2007 06 01 ',
 '1989 04 01 ',
 '1999 09 01 ',
 '1980 10 01 ',
 '2009 12 01 ',
 '1992 07 01 ',
 '2006 05 01 ',
 '2008 08 01 ',
 '1993 02 01 ',
 '2010 02 01 ',
 '1985 04 01 ',
 '1984 09 01 ',
 '1986 04 01 ',
 '2007 04 01 ',
 '1974 09 01 ',
 '2013 09 01 ',
 '1985 07 01 ',
 '2004 08 01 ',
 '2012 05 01 ',
 '1977 02 01 ',
 '1987 01 01 ',
 '1983 09 01 ',
 '2013 01 01 ',
 '2010 03 01 ',
 '2009 08 01 ',
 '2007 09 01 ',
 '2011 12 01 ',
 '2004 01 01 ',
 '1995 11 01 ',
 '2008 09 01 ',
 '1983 02 01 ',
 '1983 03 01 ',
 '1979 08 01 ',
 '2009 01 01 ',
 '1993 01 01 ',
 '1974 03 01 ',
 '1994 01 01 ',
 '1992 12 01 ',
 '2004 11 01 ',
 '1977 01 01 ',
 '2002 03 01 ',
 '2000 02 01 ',
 '2004 05 01 ',
 '2006 07 01 ',
 '1994 02 01 ',
 '1977 04 01 ',
 '1992 10 01 ',
 '1995 02 01 ',
 '1989 02 01 ',
 '1978 12 01 ',
 '2007 01 01 ',
 '1976 06 01 ',
 '2011 05 01 ',
 '1975 03 01 ',
 '1978 01 01 ',
 '1975 07 01 ',
 '2012 11 01 ',
 '1999 06 02 ',
 '1991 10 01 ',
 '1973 03 01 ',
 '1996 10 01 ',
 '2007 06 01 ',
 '1995 10 01 ',
 '1999 04 01 ',
 '2001 05 01 ',
 '2000 03 01 ',
 '1988 04 01 ',
 '1993 12 01 ',
 '1974 06 01 ',
 '1997 11 01 ',
 '1986 07 01 ',
 '1973 02 01 ',
 '1978 03 01 ',
 '2007 12 01 ',
 '1998 04 01 ',
 '2005 03 01 ',
 '1980 05 01 ',
 '2007 11 01 ',
 '1976 03 01 ',
 '1998 06 01 ',
 '2005 06 01 ',
 '1973 10 01 ',
 '2005 09 01 ',
 '1980 03 01 ',
 '2005 12 01 ',
 '1987 05 01 ',
 '2004 05 01 ',
 '1974 08 01 ',
 '1986 03 01 ',
 '1997 10 01 ',
 '1993 03 01 ',
 '1981 03 01 ',
 '2003 09 01 ',
 '1993 10 01 ',
 '1983 01 01 ',
 '1994 07 01 ',
 '2008 12 01 ',
 '1980 10 01 ',
 '2003 08 01 ',
 '1975 12 01 ',
 '2010 11 01 ',
 '1997 07 01 ',
 '2014 07 01 ',
 '2001 09 01 ',
 '1986 08 01 ',
 '1978 01 01 ',
 '1975 09 01 ',
 '2009 01 01 ',
 '1995 05 01 ',
 '1989 08 01 ',
 '2000 11 01 ',
 '1973 06 01 ',
 '1999 02 01 ',
 '2001 06 01 ',
 '1978 12 01 ',
 '2009 08 01 ',
 '1973 07 01 ',
 '2014 01 01 ',
 '1975 09 01 ',
 '2012 12 01 ',
 '1999 05 01 ',
 '1989 07 01 ',
 '2009 07 01 ',
 '1998 11 01 ',
 '1995 03 01 ',
 '2009 02 01 ',
 '1988 08 01 ',
 '2007 04 01 ',
 '2000 05 01 ',
 '2012 04 01 ',
 '2001 10 01 ',
 '1977 02 01 ',
 '2008 08 01 ',
 '1983 02 01 ',
 '1979 05 01 ',
 '1992 01 01 ',
 '2008 11 01 ',
 '2014 12 01 ',
 '1974 04 01 ',
 '1981 10 01 ',
 '1986 10 01 ',
 '1973 03 01 ',
 '1994 12 01 ',
 '1999 08 01 ',
 '2010 10 01 ',
 '1994 10 01 ',
 '2007 01 01 ',
 '2010 08 01 ',
 '1990 03 01 ',
 '2016 11 01 ',
 '2004 04 01 ',
 '1973 02 01 ',
 '1987 07 01 ',
 '2000 08 01 ',
 '1975 08 01 ',
 '1977 05 01 ',
 '2000 03 01 ',
 '1984 09 01 ',
 '1973 04 01 ',
 '1986 12 01 ',
 '1979 04 01 ',
 '2004 07 01 ',
 '1984 11 01 ',
 '2016 05 01 ',
 '2007 12 01 ',
 '1982 11 01 ',
 '1981 06 01 ',
 '2013 04 01 ',
 '1999 04 01 ',
 '2006 05 01 ',
 '1978 10 01 ',
 '1989 12 01 ',
 '1974 02 01 ',
 '1986 11 01 ',
 '1983 04 01 ',
 '2014 10 01 ',
 '1989 06 01 ',
 '1980 09 01 ',
 '1992 09 01 ',
 '2000 09 01 ',
 '1981 07 01 ',
 '2008 01 01 ',
 '2002 04 01 ',
 '1985 07 01 ',
 '2010 05 01 ',
 '2002 08 01 ',
 '1994 01 01 ',
 '2004 12 01 ',
 '2003 03 01 ',
 '1991 07 01 ',
 '1982 07 01 ',
 '1984 01 01 ',
 '2000 01 01 ',
 '2001 01 01 ',
 '1982 01 01 ',
 '1998 01 01 ',
 '2012 01 01 ',
 '1991 01 01 ',
 '1988 01 01 ',
 '2014 01 01 ',
 '2016 01 01 ',
 '1976 01 01 ',
 '1981 01 01 ',
 '2011 01 01 ',
 '1997 01 01 ',
 '2003 01 01 ',
 '1983 01 01 ',
 '1999 01 01 ',
 '2010 01 01 ',
 '1975 01 01 ',
 '1972 01 01 ',
 '2015 01 01 ',
 '1989 01 01 ',
 '1994 01 01 ',
 '1993 01 01 ',
 '1996 01 01 ',
 '2013 01 01 ',
 '1974 01 01 ',
 '1990 01 01 ',
 '1995 01 01 ',
 '2004 01 01 ',
 '1987 01 01 ',
 '1973 01 01 ',
 '1992 01 01 ',
 '1977 01 01 ',
 '1985 01 01 ',
 '2007 01 01 ',
 '2009 01 01 ',
 '1986 01 01 ',
 '1978 01 01 ',
 '2002 01 01 ',
 '1979 01 01 ',
 '2006 01 01 ',
 '2008 01 01 ',
 '2005 01 01 ',
 '1980 01 01 ']

In [89]:
# Make the dataframe
dataframe1 = pd.DataFrame(splitlist)
dataframe1.head()

             0
0  1993 03 25
1  1985 06 18
2  1971 07 08
3  1975 09 27
4  1996 02 06

In [90]:
dataframe1.columns = ['Date']
dataframe1.head()

          Date
0  1993 03 25
1  1985 06 18
2  1971 07 08
3  1975 09 27
4  1996 02 06

In [91]:
# Make 3 columns

dataframe1[['year','month','day']] = (dataframe1.Date.str.split().apply(lambda x: 
                                    pd.Series({'day':int(x[0]),'month':int(x[1]),'year':int(x[-1])})))

In [92]:
dataframe1.head()

          Date  year  month  day
0  1993 03 25   1993      3   25
1  1985 06 18   1985      6   18
2  1971 07 08   1971      7    8
3  1975 09 27   1975      9   27
4  1996 02 06   1996      2    6

In [93]:
# Sort columns together to maintain row order
df_final = dataframe1.sort_values(['year','month','day'])
df_final.index.names = ['Index']

In [94]:
df_final

              Date  year  month  day
Index
9      1971 04 10   1971      4   10
84     1971 05 18   1971      5   18
2      1971 07 08   1971      7    8
53     1971 07 11   1971      7   11
28     1971 09 12   1971      9   12
474    1972 01 01   1972      1    1
153    1972 01 13   1972      1   13
13     1972 01 26   1972      1   26
129    1972 05 06   1972      5    6
98     1972 05 13   1972      5   13
111    1972 06 10   1972      6   10
225    1972 06 15   1972      6   15
31     1972 07 20   1972      7   20
171    1972 10 04   1972     10    4
191    1972 11 30   1972     11   30
486    1973 01 01   1973      1    1
335    1973 02 01   1973      2    1
415    1973 02 01   1973      2    1
36     1973 02 14   1973      2   14
323    1973 03 01   1973      3    1
405    1973 03 01   1973      3    1
422    1973 04 01   1973      4    1
375    1973 06 01   1973      6    1
380    1973 07 01   1973      7    1
345    1973 10 01   1973     10    1
57     1973 12 01   1973     12    1
481    1974 01 01   1974      1    1
436    1974 02 01   1974      2    1
104    1974 02 24   1974      2   24
299    1974 03 01   1974      3    1
...            ...   ...    ...  ...
220    2012 06 25   2012      6   25
208    2012 09 01   2012      9    1
243    2012 09 01   2012      9    1
139    2012 10 21   2012     10   21
320    2012 11 01   2012     11    1
383    2012 12 01   2012     12    1
244    2013 01 01   2013      1    1
286    2013 01 01   2013      1    1
480    2013 01 01   2013      1    1
431    2013 04 01   2013      4    1
279    2013 09 01   2013      9    1
198    2013 10 11   2013     10   11
381    2014 01 01   2014      1    1
463    2014 01 01   2014      1    1
366    2014 07 01   2014      7    1
255    2014 10 01   2014     10    1
439    2014 10 01   2014     10    1
401    2014 12 01   2014     12    1
475    2015 01 01   2015      1    1
257    2015 09 01   2015      9    1
152    2015 09 28   2015      9   28
235    2015 10 01   2015     10    1
464    2016 01 01   2016      1    1
253    2016 02 01   2016      2    1
231    2016 05 01   2016      5    1
427    2016 05 01   2016      5    1
141    2016 05 30   2016      5   30
186    2016 10 13   2016     10   13
161    2016 10 19   2016     10   19
413    2016 11 01   2016     11    1

[500 rows x 4 columns]

In [95]:
df_final.index.values

array([  9,  84,   2,  53,  28, 474, 153,  13, 129,  98, 111, 225,  31,
       171, 191, 486, 335, 415,  36, 323, 405, 422, 375, 380, 345,  57,
       481, 436, 104, 299, 162, 154, 402,  95,  73, 108, 156, 332, 182,
        82, 351, 278, 214, 155, 223, 473,  49, 317,  11, 319,  40, 418,
       165, 370, 382,   3,  50, 363, 219, 465, 237,  23, 342, 204, 258,
       315,  27,  93,  17, 303, 488, 283, 395, 309, 419, 123,  19, 117,
       232,  72, 189, 318, 369, 493, 239, 148, 105, 336,   6, 200,  81,
        65, 434, 164, 313, 378, 495, 424, 398,   5, 254, 296,  75, 167,
        21, 259, 499, 347, 150,  78, 340, 441, 267, 361, 221, 466,  39,
       134, 197, 355, 430,  80, 246, 444,  85, 215, 263,  74, 403, 458,
        16,  25, 127, 454,  70,  44,  59, 103, 112, 429,  88, 179, 358,
       470, 205, 294, 397, 137, 295,  35, 438, 247, 209,  61, 107, 285,
       175,  99, 455,  24, 275, 421,  48, 426, 489, 136,  30, 274,  10,
       178,   1, 280, 447, 185, 228, 135,  69, 492, 199, 352,   8, 276,
       230, 334,  96,  38, 368, 261, 404, 168,  29, 437, 423,  54, 284,
       485,  68,  32, 349,  41,  63, 416,  55, 130, 116,  76, 462, 330,
        37, 256, 390, 216, 174, 180, 476, 312, 265, 115,  71, 218, 202,
       440, 385, 373, 210,  89, 149,  26,   7, 435, 482, 177, 157, 412,
        22, 194,  14, 151, 233, 206, 245, 122,  94, 461, 226,  97,  91,
        51,  33, 453,  67,  46, 322,  66, 399, 487, 138,  62, 211,  52,
       269, 119, 100, 442, 310, 143, 301, 113, 298, 478, 272, 354,   0,
       249, 192,  86, 172, 357, 331, 300, 450, 477, 163, 308, 196,  47,
       133, 359,  64,  42, 409, 406, 238, 483, 193, 311, 140, 388,  56,
       236, 372, 110, 248,  60, 181, 203, 326,  90, 169, 292, 479, 142,
         4, 124, 324, 121, 131, 166, 468, 365, 213,  87, 353, 101, 333,
       114, 459,  45, 338,  18, 222, 343,  20, 224,  12,  79, 387, 251,
       120, 471,  77, 376, 327, 432, 384, 321, 212, 407, 266, 145, 201,
       456, 260, 305, 329, 420, 392, 417, 190, 158, 443,  83, 374, 457,
       125, 328, 159, 147, 195, 377, 367, 394, 494, 304, 446,  43, 262,
       128, 102, 449, 184, 469, 452, 234, 362, 356, 144, 291, 484, 188,
       414,  92, 241, 306, 350, 425, 281, 207, 126, 302, 146, 451, 498,
       339, 250, 344, 346, 348, 496, 106, 118, 270, 433, 307, 173, 252,
       314, 410, 490, 277, 391, 264, 325, 289, 160, 341, 132, 337, 428,
       445, 497, 187, 183, 271, 396, 293, 400, 360, 297, 371, 491, 389,
       386, 288, 379, 268, 472, 273, 287, 448, 176, 411, 408, 242, 364,
        58, 467, 170,  15, 240, 316, 229, 217, 109, 227, 290, 460, 393,
       282,  34, 220, 208, 243, 139, 320, 383, 244, 286, 480, 431, 279,
       198, 381, 463, 366, 255, 439, 401, 475, 257, 152, 235, 464, 253,
       231, 427, 141, 186, 161, 413])

In [96]:
last_list = df_final.index.get_values().tolist()

In [97]:
index_series = pd.Series(last_list)

In [98]:
index_series

0        9
1       84
2        2
3       53
4       28
5      474
6      153
7       13
8      129
9       98
10     111
11     225
12      31
13     171
14     191
15     486
16     335
17     415
18      36
19     323
20     405
21     422
22     375
23     380
24     345
25      57
26     481
27     436
28     104
29     299
      ...
470    220
471    208
472    243
473    139
474    320
475    383
476    244
477    286
478    480
479    431
480    279
481    198
482    381
483    463
484    366
485    255
486    439
487    401
488    475
489    257
490    152
491    235
492    464
493    253
494    231
495    427
496    141
497    186
498    161
499    413
Length: 500, dtype: int64

In [99]:
# df_final.iloc[[100,150,300,321]]