---

_You are currently looking at **version 1.0** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-text-mining/resources/d9pwm) course resource._

---

# Assignment 1

In this assignment, you'll be working with messy medical data and using regex to extract relevant infromation from the data. 

Each line of the `dates.txt` file corresponds to a medical note. Each note has a date that needs to be extracted, but each date is encoded in one of many formats.

The goal of this assignment is to correctly identify all of the different date variants encoded in this dataset and to properly normalize and sort the dates. 

Here is a list of some of the variants you might encounter in this dataset:
* 04/20/2009; 04/20/09; 4/20/09; 4/3/09
* Mar-20-2009; Mar 20, 2009; March 20, 2009;  Mar. 20, 2009; Mar 20 2009;
* 20 Mar 2009; 20 March 2009; 20 Mar. 2009; 20 March, 2009
* Mar 20th, 2009; Mar 21st, 2009; Mar 22nd, 2009
* Feb 2009; Sep 2009; Oct 2010
* 6/2008; 12/2009
* 2009; 2010

Once you have extracted these date patterns from the text, the next step is to sort them in ascending chronological order accoring to the following rules:
* Assume all dates in xx/xx/xx format are mm/dd/yy
* Assume all dates where year is encoded in only two digits are years from the 1900's (e.g. 1/5/89 is January 5th, 1989)
* If the day is missing (e.g. 9/2009), assume it is the first day of the month (e.g. September 1, 2009).
* If the month is missing (e.g. 2010), assume it is the first of January of that year (e.g. January 1, 2010).

With these rules in mind, find the correct date in each note and return a pandas Series in chronological order of the original Series' indices.

For example if the original series was this:

    0    1999
    1    2010
    2    1978
    3    2015
    4    1985

Your function should return this:

    0    2
    1    4
    2    0
    3    1
    4    3

Your score will be calculated using [Kendall's tau](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient), a correlation measure for ordinal data.

*This function should return a Series of length 500 and dtype int.*

In [4]:
import pandas as pd            

doc = []
with open('dates.txt') as file:   # /Users/karenyang/Desktop/course4/
    for line in file:
        doc.append(line)

df = pd.Series(doc)
df.head(10)

0         03/25/93 Total time of visit (in minutes):\n
1                       6/18/85 Primary Care Doctor:\n
2    sshe plans to move as of 7/8/71 In-Home Servic...
3                7 on 9/27/75 Audit C Score Current:\n
4    2/6/96 sleep studyPain Treatment Pain Level (N...
5                    .Per 7/06/79 Movement D/O note:\n
6    4, 5/18/78 Patient's thoughts about current su...
7    10/24/89 CPT Code: 90801 - Psychiatric Diagnos...
8                         3/7/86 SOS-10 Total Score:\n
9             (4/10/71)Score-1Audit C Score Current:\n
dtype: object

In [5]:
def date_sorter():
    
    # Your code here
    
    import re
    
    df[[21]] = re.sub(r'210/21/79', '10/21/79', df[21])
    df[[235]] = re.sub(r'pOct 2015', 'Oct 2015', df[235])
    df[[245]] = re.sub(r'lNovember 1990', '01 November 1990', df[245])
    df[[256]] = re.sub(r'IAug 1988', 'Aug 1988', df[256])
    df[[265]] = re.sub(r'/', '', df[265])
    df[[271]] = re.sub(r'708-810-7787 ', '', df[271])
    df[[274]] = re.sub(r'7HH, April 1985', 'April 1985', df[274])
    df[[281]] = re.sub(r'yAug 2004', 'Aug 2004', df[281])
    df[[284]] = re.sub(r'- Jan 1987', 'Jan 1987', df[284])
    df[[285]] = re.sub(r'sSep 1983 GSW', 'Sep 1983 GSW', df[285])
    df[[333]] = re.sub(r'sNovember 1997', 'November 1997', df[333])
    df[[460]] = re.sub(r'1 Ex-smoker : quit 2012', 'Ex-smoker : quit 2012 ', df[460])
    df[[461]] = re.sub(r'. Age 16, 1991,', '1991', df[461])
    df[[462]] = re.sub(r'sLexapro (1988-now): Good response (anxiety)', '1988', df[462])
    df[[465]] = re.sub(r'.Age, 19, 1976, ', '1976 ', df[465])
    df[[466]] = re.sub(r's1981 ', '1981 ', df[466])
    df[[467]] = re.sub(r'aS/P ', '', df[467])
    df[[479]] = re.sub(r'(1993)', '1993', df[479])
    df[[487]] = re.sub(r'appendectomy s/p delivery 1992', '1992', df[487])
    df[[488]] = re.sub(r': s/p nephrectomy 1977', '1977', df[488])
    df[[490]] = re.sub(r'Lab: B12 969 2007', '2007 ', df[490])
    
    
    expression1 = r'\d{,2}[/-]\d{,2}[/-]\d{2,4}'

    list1 = []
    for line in df[0:125]:
        result1 = re.findall(expression1, line)
        if result1 != []:
            list1.append(result1[0])
            
    from dateutil.parser import parse
    lista = []

    for item in list1:
        a = str(parse(item , dayfirst=False))
        lista.append(a)
        
    expression2 = r'(?:\d{0,2} )?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,\s]* (?:\d{ ,2}, )?\d{4}'
    expression3 = r'(?:\d{0,2} )?(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,]* \d{0,2}[,.\s]*\d{2,4}'

    list2 = []
    for line in df[125:228]:

        result2 = re.findall(expression2, line)
        if result2 != []:
            list2.append(result2[0])
        else:
            result2 = re.findall(expression3, line)
            list2.append(result2[0])
            
    listb = []
    for item in list2:
        b = str(parse(item, dayfirst=False))
        listb.append(b)
        
        
        
    expression4 = r'(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,]* (?:\d{ ,2}, )?\d{4}'
              
    list4 = []
    for line in df[228:321]:

        result4 = re.findall(expression4, line)
        if result4 != []:
            list4.append(result4[0])
        # correct misspellings for 'Decemeber 1978' and 'Janaury 1993'
    list4[-8] = "December 1978"
    list4[-23] = 'January 1993'
    
    list44 = []
    for item in list4:
        x = "01 " + item
        list44.append(x)

    listc = []
    for item in list44:
        c = str(parse(item, dayfirst=False))
        listc.append(c)
        
        
        
    expression5 = r'(?:\d{1,2})(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,\w]* (?:\d{ ,2}, )?\d{4}'
    list5 = []
    result13 = re.findall(expression5, "2June, 1999")
    x = result13[0][0] + ' ' + result13[0][1:] 
    list5.append(x)
    
    listd = []
    for item in list5:
        d = str(parse(item, dayfirst=False))
        listd.append(d)
        
        
        
    expression6 = r'(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z.,]* [.,\s]?\d{4}'

    list6 = []
    for line in df[322:345]:
        result6 = re.findall(expression6, line)
        if result6 != []:
            list6.append(result6[0])
            
    list66 = []
    for item in list6:
        x = "01 " + item
        list66.append(x)
    
    liste = []
    for item in list66:
        e = str(parse(item, dayfirst=False))
        liste.append(e)
        
        
               
    expression7 = r'\d{,2}[/-]\d{2,4}'

    list7 = []
    for line in df[343:455]:
        result7 = re.findall(expression7, line)
        if result7 != []:
            list7.append(result7[0])
            
    temp = []
    for i in list7:
        x = i.split('/')
        temp.append(x)
            
    list77 = []
    for i in temp:
        b = i[0] + "/01/" + i[1]
        list77.append(b)
    
    listf = []
    for item in list77:
        f = str(parse(item, dayfirst=False))
        listf.append(f)
  
        
    expression8  = r'\d{4}'

    list8 = []
    for line in df[455:]:
        result8 = re.findall(expression8, line)
        if result8 != []:
            list8.append(result8[0])
            
    list88 = []
    for item in list8:
        x = "01/01/" + item
        list88.append(x)
        
    listg = []
    for item in list88:
        g = str(parse(item, dayfirst=False))
        listg.append(g)

        
    final_list = lista + listb + listc + listd + liste + listf + listg
    
    second_list = []

    for date in final_list:
        x = date.replace('00:00:00',"")
        second_list.append(x)
        
    # add white space   
    splitlist =[]
    for date in second_list:
        b = date.replace('-', ' ')
        splitlist.append(b)
        
    # make dataframe
    dataframe1 = pd.DataFrame(splitlist)
    dataframe1.columns = ['Date']
    
    # split date across 3 columns
    dataframe1[['year','month','day']] = (dataframe1.Date.str.split().apply(lambda x: 
                                    pd.Series({'day':int(x[0]),'month':int(x[1]),'year':int(x[-1])})))
    # Sort columns together to maintain row order
    df_final = dataframe1.sort_values(['year','month','day'])
    df_final.index.names = ['Index']
    
    last_list = df_final.index.get_values().tolist()
    
    index_series = pd.Series(last_list)
    
        
    # Your answer here    
    return index_series

In [6]:
date_sorter()

0        9
1       84
2        2
3       53
4       28
5      474
6      153
7       13
8      129
9       98
10     111
11     225
12      31
13     171
14     191
15     486
16     335
17     415
18      36
19     323
20     405
21     422
22     375
23     380
24     345
25      57
26     481
27     436
28     104
29     299
      ...
470    220
471    208
472    243
473    139
474    320
475    383
476    244
477    286
478    480
479    431
480    279
481    198
482    381
483    463
484    366
485    255
486    439
487    401
488    475
489    257
490    152
491    235
492    464
493    253
494    231
495    427
496    141
497    186
498    161
499    413
Length: 500, dtype: int64